<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Комментарии");
?><?$APPLICATION->IncludeComponent(
	"bitrix:forum",
	"",
	Array(
		"THEME" => "blue",
		"SHOW_TAGS" => "N",
		"SEO_USER" => "Y",
		"SEO_USE_AN_EXTERNAL_SERVICE" => "Y",
		"SHOW_FORUM_USERS" => "Y",
		"SHOW_SUBSCRIBE_LINK" => "N",
		"SHOW_AUTH_FORM" => "N",
		"SHOW_NAVIGATION" => "Y",
		"SHOW_LEGEND" => "Y",
		"SHOW_STATISTIC_BLOCK" => array("STATISTIC","BIRTHDAY","USERS_ONLINE"),
		"SHOW_FORUMS" => "Y",
		"SHOW_FIRST_POST" => "N",
		"SHOW_AUTHOR_COLUMN" => "N",
		"TMPLT_SHOW_ADDITIONAL_MARKER" => "",
		"PATH_TO_SMILE" => "/bitrix/images/forum/smile/",
		"PAGE_NAVIGATION_TEMPLATE" => "forum",
		"PAGE_NAVIGATION_WINDOW" => "5",
		"AJAX_POST" => "N",
		"WORD_WRAP_CUT" => "23",
		"WORD_LENGTH" => "50",
		"USE_LIGHT_VIEW" => "Y",
		"SEF_MODE" => "N",
		"CHECK_CORRECT_TEMPLATES" => "Y",
		"FID" => array("1","3"),
		"USER_PROPERTY" => array(),
		"USER_FIELDS" => array(),
		"HELP_CONTENT" => "",
		"RULES_CONTENT" => "",
		"FORUMS_PER_PAGE" => "10",
		"TOPICS_PER_PAGE" => "10",
		"MESSAGES_PER_PAGE" => "100",
		"PATH_TO_AUTH_FORM" => "",
		"TIME_INTERVAL_FOR_USER_STAT" => "10",
		"DATE_FORMAT" => "d.m.Y",
		"DATE_TIME_FORMAT" => "d.m.Y H:i:s",
		"USE_NAME_TEMPLATE" => "N",
		"NAME_TEMPLATE" => "",
		"IMAGE_SIZE" => "500",
		"ATTACH_MODE" => array("NAME"),
		"ATTACH_SIZE" => "90",
		"EDITOR_CODE_DEFAULT" => "N",
		"SEND_MAIL" => "E",
		"SEND_ICQ" => "A",
		"SET_NAVIGATION" => "Y",
		"SET_TITLE" => "Y",
		"SET_DESCRIPTION" => "Y",
		"SET_PAGE_PROPERTY" => "Y",
		"USE_RSS" => "Y",
		"SHOW_FORUM_ANOTHER_SITE" => "Y",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "3600",
		"CACHE_NOTES" => "",
		"CACHE_TIME_USER_STAT" => "60",
		"CACHE_TIME_FOR_FORUM_STAT" => "3600",
		"RSS_TYPE_RANGE" => array("RSS1","RSS2","ATOM"),
		"RSS_CACHE" => "1800",
		"RSS_COUNT" => "30",
		"RSS_TN_TITLE" => "",
		"RSS_TN_DESCRIPTION" => "",
		"SHOW_VOTE" => "N",
		"SHOW_RATING" => "N",
		"VARIABLE_ALIASES" => Array(
			"FID" => "FID",
			"TID" => "TID",
			"MID" => "MID",
			"UID" => "UID"
		)
	),
false
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>