<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Указы президента РФ");
?><h1 style="color: #464646; background-color: #ffffff;">Указы президента РФ</h1>
<ol>
	<li><a href="http://pravo.gov.ru/proxy/ips/?docbody=&nd=102033512&intelsearch=%EE+%E3%EE%F1%F3%E4%E0%F0%F1%F2%E2%E5%ED%ED%FB%F5+%E4%EE%EB%E6%ED%EE%F1%F2%FF%F5+32" target="_blank" style="color: #00749e;">№32 "О государственных должностях Российской Федерации"</a></li>
	<li><a href="http://pravo.gov.ru/proxy/ips/?docbody=&nd=102038185&intelsearch=%EE%E1+%F3%F2%E2%E5%F0%E6%E4%E5%ED%E8%E8+%EF%F0%E5%F7%ED%FF+%F1%E2%E5%E4%E5%ED%E8%E9+1203" target="_blank" style="color: #00749e;">№1203 "Об утверждении перечня сведений, отнесенных к государственной тайне"</a></li>
	<li><a href="http://pravo.gov.ru/proxy/ips/?docbody=&nd=102045711&intelsearch=%EE%E1+%F3%F2%E2%E5%F0%E6%E4%E5%ED%E8%E8+%EF%F0%E5%F7%ED%FF+%F1%E2%E5%E4%E5%ED%E8%E9+188" target="_blank" style="color: #00749e;">№188 "Об утверждении перечня сведений конфедициального характера"</a></li>
	<li><a href="http://pravo.gov.ru/proxy/ips/?docbody=&nd=102077149&intelsearch=%EE%E1+%F3%F2%E2%E5%F0%E6%E4%E5%ED%E8%E8+%EE%E1%F9%E8%F5+%EF%F0%E8%ED%F6%E8%EF%EE%E2+885" target="_blank" style="color: #00749e;">№885 "Об утверждении общих принципов поведения государственных служащих"</a></li>
	<li><a href="http://pravo.gov.ru/proxy/ips/?docbody=&nd=102090594&intelsearch=%EE+%EF%F0%EE%E2%E5%E4%E5%ED%E8%E8+%E0%F2%F2%E5%F1%F2%E0%F6%E8%E8+110" target="_blank" style="color: #00749e;">№110 "О проведении аттестации государственных гражданских служащих Российской Федерации"</a></li>
	<li><a href="http://pravo.gov.ru/proxy/ips/?docbody=&nd=102090595&intelsearch=111+%EE+%EF%EE%F0%FF%EB%EA%E5+%F1%E4%E0%F7%E8" target="_blank" style="color: #00749e;">№111 "О порядке сдачи квалификационного экзамена государственными гражданскими служащими Российской Федерации и оценки их знаний, навыков и умений (профессионального уровня"</a></li>
	<li><a href="http://pravo.gov.ru/proxy/ips/?docbody=&nd=102090593&intelsearch=112+%EE+%EA%EE%ED%EA%F3%F0%F1%E5" target="_blank" style="color: #00749e;">№112 "О конкурсе на замещение вакантной должности государственной гражданской службы Российской Федерации"</a></li>
	<li><a href="http://pravo.gov.ru/proxy/ips/?docbody=&nd=102090592&intelsearch=113+%EE+%EF%EE%F0%FF%E4%EA%E5+%EF%F0%E8%F1%E2%EE%E5%ED%E8%FF" target="_blank" style="color: #00749e;">№113 "О порядке присвояения и сохранения классных чинов государственной гражданской службы Российской Федерации федеральными государственными гражданскими служащими</a>"</li>
	<li><a href="http://pravo.gov.ru/proxy/ips/?docbody=&nd=102129833&intelsearch=560+%EE+%EF%F0%E5%E4%EE%F1%F2%E0%E2%EB%E5%ED%E8%E8+%E3%F0%E0%E6%E4%E0%ED%E0%EC%E8%2C+%EF%F0%E5%F2%E5%ED%E4%F3%FE%F9%E8%EC%E8" target="_blank" style="color: #00749e;">№560 "О предоставлении гражданами, претендующими на замещение руководящих должностей в государственных корпорациях, фондах и иных организациях, лицами, замещающими руководящие должности в государственных корпорациях, фондах и иных организациях, сведений о доходах, б имуществе и обязательствах имущественного характера</a>"</li>
	<li><a href="http://pravo.gov.ru/proxy/ips/?docbody=&nd=102129834&intelsearch=%B9561+%22%CE%E1+%F3%F2%E2%E5%F0%E6%E4%E5%ED%E8%E8+%EF%EE%F0%FF%E4%EA%E0+%F0%E0%E7%EC%E5%F9%E5%ED%E8%FF+%F1%E2%E5%E4%E5%ED%E8%E9" target="_blank" style="color: #00749e;">№561 "Об утверждении порядка размещения сведений о доходах, об имуществе и обязательствах имущественного характера лиц, замещающих государственные должности РФ, федеральных государственных служащих и членов из семей на официальных сайтах федеральных государственных органов и государственных органов субъектов РФ и предоставления этих сведений общероссийским средствам массовой информации"&nbsp;</a></li>
	<li><a href="http://pravo.gov.ru/proxy/ips/?docbody=&nd=102132775&intelsearch=%B91065+%22%CE+%EF%F0%EE%E2%E5%F0%EA%E5+%E4%EE%F1%F2%EE%E2%E5%F0%ED%EE%F1%F2%E8+%E8+%EF%EE%EB%ED%EE%F2%FB+%F1%E2%E5%E4%E5%ED%E8%E9%2C" target="_blank" style="color: #00749e;">№1065 "О проверке достоверности и полноты сведений, представляемых гражданами, претендующими на замещение государственных должностей РФ, и лицами, замещающими государственные должности РФ, и соблюдения федеральными государственными служащими требований к служебному поведению"</a></li>
	<li><a href="http://pravo.gov.ru/proxy/ips/?docbody=&nd=102132776&intelsearch=%B91066+%EE+%EF%F0%EE%E2%E5%F0%EA%E5+%E4%EE%F1%F2%EE%E2%E5%F0%ED%EE%F1%F2%E8" target="_blank" style="color: #00749e;">№1066 "О проверке&nbsp;достоверности и полноты сведений, представляемых гражданами, претендующими на замещение государственных должностей РФ, и лицами, замещающими государственные должности РФ, и соблюдения&nbsp;ограничений лицами, замещающими государственные должности РФ"</a></li>
	<li><a href="http://pravo.gov.ru/proxy/ips/?docbody=&nd=102134437&intelsearch=%B91381+%22%CE+%F2%E8%EF%EE%E2%FB%F5+%E3%EE%F1%F3%E4%E0%F0%F1%F2%E2%E5%ED%ED%FB%F5+%E4%EE%EB%E6%ED%EE%F1%F2%FF%F5+%F1%F3%E1%FA%E5%EA%F2%EE%E2+%D0%D4%22" target="_blank" style="color: #00749e;">№1381 "О типовых государственных должностях субъектов РФ"</a></li>
	<li><a href="http://pravo.gov.ru/proxy/ips/?docbody=&nd=102306136&intelsearch=%CE+%ED%E0%F6%E8%EE%ED%E0%EB%FC%ED%EE%E9+%F1%F2%F0%E0%F2%E5%E3%E8%E8+%EF%F0%EE%F2%E8%E2%EE%E4%E5%E9%F1%F2%E2%E8%FF+%EA%EE%F0%F0%F3%EF%F6%E8%E8+%E8+%ED%E0%F6%E8%EE%ED%E0%EB%FC%ED%EE%EC+%EF%EB%E0%ED%E5" target="_blank" style="color: #00749e;">№297 " О национальной стратегии противодействия коррупции и национальном плане противодействия коррупции на 2012-1013 годы"</a></li>
	<li><a href="http://pravo.gov.ru/proxy/ips/?docbody=&nd=102139720&intelsearch=821+%EE+%EA%EE%EC%E8%F1%F1%E8%FF%F5" target="_blank" style="color: #00749e;">№821 "О комиссиях по соблюдению требований к служебному поведению федеральных государственных служащих и урегулированию конфликта интересов"</a></li>
	<li><a href="http://pravo.gov.ru/proxy/ips/?docbody=&nd=102140493&intelsearch=925+%EE+%EC%E5%F0%E0%F5" target="_blank" style="color: #00749e;">№925 "О мерах по реализации отдельных положений Федерального закона "О противодействии коррупции""</a></li>
	<li><a href="http://pravo.gov.ru/proxy/ips/?docbody=&nd=102092406&intelsearch=%EE%E1+%F3%F2%E2%E5%F0%E6%E4%E5%ED%E8%E8+%EF%EE%EB%EE%E6%E5%ED%E8%FF+609" target="_blank" style="color: #00749e;">№609 "Об утверждении положения о персональных данных государственного гражданского служащего Российской Федерации и ведении его личного дела"</a></li>
	<li><a href="http://pravo.gov.ru/proxy/ips/?docbody=&nd=102122141&intelsearch=%EE+%EC%E5%F0%E0%F5+815" target="_blank" style="color: #00749e;">№815 "О мерах по противодействию коррупции"</a></li>
	<li><a href="http://pravo.gov.ru/proxy/ips/?docbody=&nd=102306136&intelsearch=297+%ED%E0%F6%E8%EE%ED%E0%EB%FC%ED%FB%E9+%EF%EB%E0%ED" target="_blank" style="color: #00749e;">№297 "Национальный план противодействия коррупции на 2012-2013 годы"</a></li>
	<li><a href="http://pravo.gov.ru/proxy/ips/?docbody=&nd=102128327&intelsearch=261+%EE+%F4%E5%E4%E5%F0%E0%EB%FC%ED%EE%E9+%EF%F0%EE%E3%F0%E0%EC%EC%E5" target="_blank" style="color: #00749e;">№261 "О федеральной программе "Реформирование и развитие системы государственной службы РФ (2009-2013 годы)"</a></li>
	<li><a href="http://pravo.gov.ru/proxy/ips/?docbody=&nd=102129830&intelsearch=557+%EE%E1+%F3%F2%E2%E5%F0%E6%E4%E5%ED%E8%E8+%EF%E5%F0%E5%F7%ED%FF" target="_blank" style="color: #00749e;">№557 "Об утверждении перечня должностей федеральной государственной службы, при назначении на которые граждане и при замещении которых федеральные государственные служащие обязаны предоставлять сведения о своих доходах, об имуществе и обязательствах имущественного характера своих супруги (супруга) и несовершеннолетних детей"</a></li>
	<li><a href="http://pravo.gov.ru/proxy/ips/?docbody=&nd=102129832&intelsearch=559+%EE+%EF%F0%E5%E4%F1%F2%E0%E2%EB%E5%ED%E8%E8" target="_blank" style="color: #00749e;">№558 "О представлении гражданами, претендующими на замещение государственных должностей РФ, и лицами, замещающими государственные должности РФ, сведений о доходах, об имуществе и обязательствах имуществнного характера"</a></li>
	<li><a href="http://pravo.gov.ru/proxy/ips/?docbody=&nd=102129831&intelsearch=558+%EE+%EF%F0%E5%E4%F1%F2%E0%E2%EB%E5%ED%E8%E8" target="_blank" style="color: #00749e;">№558 "О представлении гражданами, претендующими на замещение &nbsp;должностей федеральной государственной службы и федеральными государственными служащими, сведений о доходах, об имуществе и обязательствах имуществнного характера"</a></li>
	<li><a href="/content_docs/Zakoni/ukaz_309.pdf" target="_blank" style="color: #00749e;">№ 309 "О мерах по реализации отдельных положений федерального закона "О противодействии коррупции" от 2 апреля 2013 года</a></li>
	<li><a href="/content_docs/Zakoni/ukaz_310.pdf" style="color: #00749e;">№ 310 "О мерах по реализации отдельных положений федерального закона "О контроле за соответствием расходов лиц, замещающих государственные должности, и иных лиц их доходам"</a></li>
	<li><a href="/content_docs/Zakoni/Ukaz%20Prez%20613.rtf" style="color: #00749e;">№ 613 "Вопросы противодействия коррупции"</a></li>
</ol>
<br><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>