<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 0.2b
 */

//
// Database `u266638`
//

// `u266638`.`collections`
$collections = array(
  array('name' => 'Cocktail Verde-Salvia','images' => '108_1_1s, 108_1_1b','images_b' => ''),
  array('name' => 'Chill Out','images' => 'pic_s, pic_b','images_b' => ''),
  array('name' => 'Albany Teka','images' => 'Albany_Teka.jpg,Albany_Teka_1.jpg,Albany_Teka_2.jpg,Albany_Teka_3.jpg','images_b' => 'Albany_Teka.jpg,Albany_Teka_1.jpg,Albany_Teka_2.jpg,Albany_Teka_3.jpg'),
  array('name' => 'Albany Siena','images' => 'Albany_Siena.jpg,Albany_Siena_1.jpg,Albany_Siena_2.jpg','images_b' => 'Albany_Siena.jpg,Albany_Siena_1.jpg,Albany_Siena_2.jpg'),
  array('name' => 'Isla ','images' => '','images_b' => ''),
  array('name' => 'Blanco Natural','images' => 'Blanco_Natural.jpg,Blanco_Natural_1.jpg,Blanco_Natural_2.jpg','images_b' => 'Blanco_Natural.jpg,Blanco_Natural_1.jpg,Blanco_Natural_2.jpg'),
  array('name' => 'Rojo','images' => 'Rojo.jpg','images_b' => 'Rojo.jpg'),
  array('name' => 'Natural','images' => 'Natural.jpg,Natural_1.jpg,Natural_2.jpg,Natural_3.jpg,Natural_4.jpg,Natural_5.jpg,Natural_6.jpg','images_b' => 'Natural.jpg,Natural_1.jpg,Natural_2.jpg,Natural_3.jpg,Natural_4.jpg,Natural_5.jpg,Natural_6.jpg'),
  array('name' => 'Piscina','images' => 'Piscina.jpg,Piscina_1.jpg,Piscina_2.jpg,Piscina_3.jpg,Piscina_4.jpg,Piscina_5.jpg,Piscina_6.jpg,Piscina_7.jpg,Piscina_8.jpg,Piscina_9.jpg','images_b' => 'Piscina.jpg,Piscina_1.jpg,Piscina_2.jpg,Piscina_3.jpg,Piscina_4.jpg,Piscina_5.jpg,Piscina_6.jpg,Piscina_7.jpg,Piscina_8.jpg,Piscina_9.jpg'),
  array('name' => 'Rodamanto','images' => 'Rodamanto.jpg,Rodamanto_1.jpg,Rodamanto_2.jpg,Rodamanto_3.jpg,Rodamanto_4.jpg,Rodamanto_5.jpg,Rodamanto_6.jpg,Rodamanto_7.jpg','images_b' => 'Rodamanto.jpg,Rodamanto_1.jpg,Rodamanto_2.jpg,Rodamanto_3.jpg,Rodamanto_4.jpg,Rodamanto_5.jpg,Rodamanto_6.jpg,Rodamanto_7.jpg'),
  array('name' => 'Aldonza','images' => 'Aldonza.jpg','images_b' => 'Aldonza.jpg'),
  array('name' => 'Riansares','images' => 'Riansares.jpg,Riansares_1.jpg,Riansares_2.jpg,Riansares_3.jpg','images_b' => 'Riansares.jpg,Riansares_1.jpg,Riansares_2.jpg,Riansares_3.jpg'),
  array('name' => 'Tajo','images' => 'Tajo.jpg,Tajo_1.jpg','images_b' => 'Tajo.jpg,Tajo_1.jpg'),
  array('name' => 'Negro Alasal','images' => 'Negro_Alasal.jpg,Negro_Alasal_1.jpg','images_b' => 'Negro_Alasal.jpg,Negro_Alasal_1.jpg'),
  array('name' => 'Granada','images' => 'Granada.jpg,Granada_1.jpg','images_b' => 'Granada.jpg,Granada_1.jpg'),
  array('name' => 'Medina Azahara','images' => 'Medina_Azahara.jpg','images_b' => 'Medina_Azahara.jpg'),
  array('name' => 'Mezquta','images' => 'Mezquta.jpg','images_b' => 'Mezquta.jpg'),
  array('name' => 'Pozoblanco','images' => 'Pozoblanco.jpg','images_b' => 'Pozoblanco.jpg'),
  array('name' => 'Campestre','images' => 'Campestre.jpg','images_b' => 'Campestre.jpg'),
  array('name' => 'Vega Camel','images' => 'Vega_Camel.jpg','images_b' => 'Vega_Camel.jpg'),
  array('name' => 'Vega Vision','images' => 'Vega_Vision.jpg','images_b' => 'Vega_Vision.jpg'),
  array('name' => 'Vega Gris','images' => 'Vega_Gris.jpg,Vega_Gris_1.jpg','images_b' => 'Vega_Gris.jpg,Vega_Gris_1.jpg'),
  array('name' => 'Constructa C-1','images' => '','images_b' => ''),
  array('name' => 'Constructa C-3','images' => '','images_b' => ''),
  array('name' => 'Constructa C-4','images' => '','images_b' => ''),
  array('name' => 'Constructa C-5','images' => '','images_b' => ''),
  array('name' => 'Atlas','images' => '','images_b' => ''),
  array('name' => 'Taiga','images' => 'Taiga.jpg,Taiga_1.jpg','images_b' => 'Taiga.jpg,Taiga_1.jpg'),
  array('name' => 'MONT MARTE','images' => 'MONT_MARTE.jpg','images_b' => 'MONT_MARTE.jpg'),
  array('name' => 'QUARZIT','images' => 'QUARZIT.jpg','images_b' => 'QUARZIT.jpg'),
  array('name' => 'CASCATA','images' => 'CASCATA.jpg','images_b' => 'CASCATA.jpg'),
  array('name' => 'Zaffiri','images' => 'Zaffiri.jpg','images_b' => 'Zaffiri.jpg'),
  array('name' => 'Cervino','images' => '','images_b' => ''),
  array('name' => 'Stone Grigio','images' => '','images_b' => ''),
  array('name' => 'Euphoria','images' => 'Euphoria.jpg,Euphoria_1.jpg','images_b' => 'Euphoria.jpg,Euphoria_1.jpg'),
  array('name' => 'PORTO','images' => 'PORTO.jpg','images_b' => 'PORTO.jpg'),
  array('name' => 'VALENCIA','images' => 'VALENCIA.jpg','images_b' => 'VALENCIA.jpg'),
  array('name' => 'STRATOS','images' => '','images_b' => ''),
  array('name' => 'AD','images' => '','images_b' => ''),
  array('name' => 'Fernstone','images' => 'Fernstone.jpg','images_b' => 'Fernstone.jpg'),
  array('name' => 'Ibiza','images' => 'Ibiza.jpg','images_b' => 'Ibiza.jpg'),
  array('name' => 'Aitana','images' => '','images_b' => ''),
  array('name' => 'Monti','images' => '','images_b' => ''),
  array('name' => 'Montblanc','images' => '','images_b' => ''),
  array('name' => 'Everest','images' => '','images_b' => ''),
  array('name' => 'Ural','images' => '','images_b' => ''),
  array('name' => 'ONIX','images' => '','images_b' => ''),
  array('name' => 'BOSTON','images' => 'BOSTON.jpg','images_b' => 'BOSTON.jpg'),
  array('name' => 'FLANDES','images' => '','images_b' => ''),
  array('name' => 'Rapunzel','images' => 'Rapunzel.jpg','images_b' => 'Rapunzel.jpg'),
  array('name' => 'AROA','images' => 'AROA.jpg','images_b' => 'AROA.jpg'),
  array('name' => 'Augusta','images' => 'Augusta.jpg','images_b' => 'Augusta.jpg'),
  array('name' => 'Renacimiento','images' => 'Renacimiento.jpg,Renacimiento_1.jpg','images_b' => 'Renacimiento.jpg,Renacimiento_1.jpg'),
  array('name' => 'Sorolla','images' => '','images_b' => ''),
  array('name' => 'Life','images' => 'Life.jpg','images_b' => 'Life.jpg'),
  array('name' => 'BLOOM','images' => 'BLOOM.jpg','images_b' => 'BLOOM.jpg'),
  array('name' => 'ECCENTRIC','images' => '','images_b' => ''),
  array('name' => 'MEDEA','images' => 'MEDEA.jpg','images_b' => 'MEDEA.jpg'),
  array('name' => 'REGINA','images' => 'REGINA.jpg','images_b' => 'REGINA.jpg'),
  array('name' => 'ORIENTAL','images' => 'ORIENTAL.jpg,ORIENTAL_1.jpg','images_b' => 'ORIENTAL.jpg'),
  array('name' => 'SINTRA','images' => 'SINTRA.jpg','images_b' => 'SINTRA.jpg'),
  array('name' => '','images' => '','images_b' => ''),
  array('name' => 'EXPERIENCE','images' => 'EXPERIENCE.jpg','images_b' => 'EXPERIENCE.jpg'),
  array('name' => 'Fresco','images' => 'Fresco.jpg,Fresco_1.jpg,Fresco_2.jpg,Fresco_3.jpg','images_b' => 'Fresco.jpg,Fresco_1.jpg,Fresco_2.jpg,Fresco_3.jpg'),
  array('name' => 'LORD','images' => 'LORD.jpg,LORD_1.jpg,LORD_2.jpg,LORD_3.jpg,LORD_4.jpg,LORD_5.jpg,LORD_6.jpg,LORD_7.jpg,LORD_8.jpg,LORD_9.jpg','images_b' => 'LORD.jpg,LORD_1.jpg,LORD_2.jpg,LORD_3.jpg,LORD_4.jpg,LORD_5.jpg,LORD_6.jpg,LORD_7.jpg,LORD_8.jpg,LORD_9.jpg'),
  array('name' => 'PARIS','images' => '','images_b' => ''),
  array('name' => 'NEBRASKA','images' => '','images_b' => ''),
  array('name' => 'Luxor','images' => 'Luxor.jpg','images_b' => 'Luxor.jpg'),
  array('name' => 'LIBERTY','images' => 'LIBERTY.jpg,LIBERTY_1.jpg,LIBERTY_2.jpg','images_b' => 'LIBERTY.jpg,LIBERTY_1.jpg,LIBERTY_2.jpg'),
  array('name' => 'Lava','images' => '','images_b' => ''),
  array('name' => 'AC','images' => '','images_b' => ''),
  array('name' => 'LENO-HAYA','images' => '','images_b' => ''),
  array('name' => '400','images' => '400.jpg,400_1.jpg','images_b' => '400.jpg,400_1.jpg'),
  array('name' => '405','images' => '405.jpg','images_b' => '405.jpg'),
  array('name' => '409','images' => '409.jpg,409_1.jpg,409_2.jpg','images_b' => '409.jpg,409_1.jpg,409_2.jpg'),
  array('name' => '410','images' => '','images_b' => ''),
  array('name' => '418','images' => '418.jpg','images_b' => '418.jpg'),
  array('name' => '603','images' => '603.jpg','images_b' => '603.jpg'),
  array('name' => '567','images' => '567.jpg,567_1.jpg','images_b' => '567.jpg,567_1.jpg'),
  array('name' => '437','images' => '','images_b' => ''),
  array('name' => '902','images' => '902.jpg,902_1.jpg,902_2.jpg','images_b' => '902.jpg,902_1.jpg,902_2.jpg'),
  array('name' => '2006','images' => '2006.jpg,2006_1.jpg','images_b' => '2006.jpg,2006_1.jpg'),
  array('name' => '2007','images' => '','images_b' => ''),
  array('name' => '333','images' => '333.jpg,333_1.jpg,333_2.jpg,333_3.jpg','images_b' => '333.jpg,333_1.jpg,333_2.jpg,333_3.jpg'),
  array('name' => '215','images' => '215.jpg','images_b' => '215.jpg'),
  array('name' => '254','images' => '254.jpg,254_1.jpg','images_b' => '254.jpg,254_1.jpg'),
  array('name' => 'Stone Ferro','images' => '','images_b' => ''),
  array('name' => 'Pordoi','images' => '','images_b' => ''),
  array('name' => 'Work','images' => 'Work.jpg,Work_1.jpg,Work_2.jpg','images_b' => 'Work.jpg,Work_1.jpg,Work_2.jpg'),
  array('name' => 'Silverstone Blu','images' => 'Silverstone_Blu.jpg','images_b' => 'Silverstone_Blu.jpg'),
  array('name' => 'Silverstone Bruciato','images' => 'Silverstone_Bruciato.jpg','images_b' => 'Silverstone_Bruciato.jpg'),
  array('name' => 'Silverstone Moka','images' => 'Silverstone_Moka.jpg','images_b' => 'Silverstone_Moka.jpg'),
  array('name' => 'Silverstone Bianco','images' => 'Silverstone_Bianco.jpg','images_b' => 'Silverstone_Bianco.jpg'),
  array('name' => 'Montalcino Antico Scuro','images' => 'Montalcino_Antico_Scuro.jpg','images_b' => 'Montalcino_Antico_Scuro.jpg'),
  array('name' => 'Montalcino Arancio','images' => '','images_b' => ''),
  array('name' => 'Montalcino Giallo','images' => '','images_b' => ''),
  array('name' => 'Monterrey Bruciato','images' => 'Monterrey_Bruciato.jpg','images_b' => 'Monterrey_Bruciato.jpg'),
  array('name' => 'Yucatan Bruciato','images' => 'Yucatan_Bruciato.jpg','images_b' => 'Yucatan_Bruciato.jpg'),
  array('name' => 'SINE DIE','images' => '','images_b' => ''),
  array('name' => 'Alta Moda','images' => 'Alta_Moda.jpg','images_b' => 'Alta_Moda.jpg'),
  array('name' => 'DIAMOND','images' => '','images_b' => ''),
  array('name' => 'Metallica','images' => 'Metallica.jpg,Metallica_1.jpg,Metallica_2.jpg','images_b' => 'Metallica.jpg,Metallica_1.jpg,Metallica_2.jpg'),
  array('name' => 'Iride','images' => '','images_b' => ''),
  array('name' => 'Quartiere Latino','images' => 'Quartiere_Latino.jpg','images_b' => 'Quartiere_Latino.jpg'),
  array('name' => 'Stardust','images' => 'Stardust.jpg,Stardust_1.jpg','images_b' => 'Stardust.jpg,Stardust_1.jpg'),
  array('name' => 'De Origin','images' => '','images_b' => ''),
  array('name' => 'Iris Beige','images' => 'Iris_Beige.jpg','images_b' => 'Iris_Beige.jpg'),
  array('name' => 'Oda','images' => 'Oda.jpg,Oda_1.jpg','images_b' => 'Oda.jpg,Oda_1.jpg'),
  array('name' => 'Sarah','images' => 'Sarah.jpg','images_b' => 'Sarah.jpg'),
  array('name' => 'Siena','images' => 'Siena.jpg','images_b' => 'Siena.jpg'),
  array('name' => 'Aramis','images' => 'Aramis.jpg','images_b' => 'Aramis.jpg'),
  array('name' => 'Monochrome','images' => 'Monochrome.jpg,Monochrome_1.jpg,Monochrome_2.jpg,Monochrome_3.jpg,Monochrome_4.jpg','images_b' => 'Monochrome.jpg,Monochrome_1.jpg,Monochrome_2.jpg,Monochrome_3.jpg,Monochrome_4.jpg'),
  array('name' => 'Dorica','images' => 'Dorica.jpg,Dorica_1.jpg,Dorica_2.jpg,Dorica_3.jpg,Dorica_4.jpg,Dorica_5.jpg','images_b' => 'Dorica.jpg,Dorica_1.jpg,Dorica_2.jpg,Dorica_3.jpg,Dorica_4.jpg,Dorica_5.jpg'),
  array('name' => 'Helsinki Beige-Naranija','images' => '','images_b' => ''),
  array('name' => 'Helsinki Blanco-Pistacho','images' => 'Helsinki_Blanco_Pistacho.jpg','images_b' => 'Helsinki_Blanco_Pistacho.jpg'),
  array('name' => 'Ranbow','images' => 'Ranbow.jpg,Ranbow_1.jpg,Ranbow_2.jpg,Ranbow_3.jpg,Ranbow_4.jpg','images_b' => 'Ranbow.jpg,Ranbow_1.jpg,Ranbow_2.jpg,Ranbow_3.jpg,Ranbow_4.jpg'),
  array('name' => 'Shine','images' => 'Shine.jpg,Shine_1.jpg','images_b' => ''),
  array('name' => 'Toledo','images' => 'Toledo.jpg,Toledo_1.jpg,Toledo_2.jpg,Toledo_3.jpg','images_b' => 'Toledo.jpg,Toledo_1.jpg,Toledo_2.jpg,Toledo_3.jpg'),
  array('name' => 'Lacche','images' => 'Lacche.jpg,Lacche_1.jpg,Lacche_2.jpg','images_b' => 'Lacche.jpg,Lacche_1.jpg,Lacche_2.jpg'),
  array('name' => 'Materia','images' => 'Materia.jpg,Materia_1.jpg,Materia_2.jpg','images_b' => 'Materia.jpg,Materia_1.jpg,Materia_2.jpg'),
  array('name' => 'Amber','images' => 'Amber.jpg','images_b' => 'Amber.jpg'),
  array('name' => 'Botticino ','images' => '','images_b' => ''),
  array('name' => 'Maiuguali','images' => '','images_b' => ''),
  array('name' => 'Terra','images' => 'Terra.jpg','images_b' => 'Terra.jpg'),
  array('name' => 'Creta Beige','images' => 'Creta_Beige.jpg,Creta_Beige_1.jpg','images_b' => 'Creta_Beige.jpg,Creta_Beige_1.jpg'),
  array('name' => 'Creta Marron','images' => 'Creta_Marron.jpg','images_b' => 'Creta_Marron.jpg'),
  array('name' => 'Lignano Beige','images' => '','images_b' => ''),
  array('name' => 'Home','images' => 'Home.jpg,Home_1.jpg','images_b' => 'Home.jpg,Home_1.jpg'),
  array('name' => 'Travertino','images' => 'Travertino.jpg,Travertino_1.jpg','images_b' => 'Travertino.jpg,Travertino_1.jpg'),
  array('name' => 'Vertigo','images' => 'Vertigo.jpg,Vertigo_1.jpg,Vertigo_2.jpg','images_b' => 'Vertigo.jpg,Vertigo_1.jpg,Vertigo_2.jpg'),
  array('name' => 'Natural','images' => 'Natural.jpg,Natural_1.jpg,Natural_2.jpg,Natural_3.jpg,Natural_4.jpg,Natural_5.jpg,Natural_6.jpg','images_b' => 'Natural.jpg,Natural_1.jpg,Natural_2.jpg,Natural_3.jpg,Natural_4.jpg,Natural_5.jpg,Natural_6.jpg'),
  array('name' => 'Atlas','images' => 'Atlas.jpg','images_b' => 'Atlas.jpg'),
  array('name' => 'Zaffiri','images' => 'Zaffiri.jpg','images_b' => 'Zaffiri.jpg'),
  array('name' => 'Cervino','images' => '','images_b' => ''),
  array('name' => 'Stone Grigio','images' => '','images_b' => ''),
  array('name' => 'LIFE','images' => 'LIFE.jpg,LIFE_1.jpg','images_b' => 'LIFE.jpg,LIFE_1.jpg'),
  array('name' => 'LUXOR','images' => 'LUXOR.jpg','images_b' => ''),
  array('name' => '2007','images' => '2007.jpg','images_b' => '2007.jpg'),
  array('name' => 'MARES','images' => 'MARES.jpg,MARES_1.jpg,MARES_2.jpg','images_b' => 'MARES.jpg,MARES_1.jpg,MARES_2.jpg'),
  array('name' => 'MARES','images' => 'MARES.jpg,MARES_1.jpg,MARES_2.jpg','images_b' => 'MARES.jpg,MARES_1.jpg,MARES_2.jpg'),
  array('name' => 'OSAKA','images' => 'OSAKA.jpg','images_b' => 'OSAKA.jpg'),
  array('name' => 'VIENA','images' => 'VIENA.jpg','images_b' => 'VIENA.jpg'),
  array('name' => 'MIERES','images' => 'MIERES.jpg','images_b' => 'MIERES.jpg'),
  array('name' => 'SIENA','images' => 'SIENA.jpg','images_b' => 'SIENA.jpg'),
  array('name' => 'TOLEDO','images' => '','images_b' => ''),
  array('name' => 'ELDA','images' => 'ELDA.jpg','images_b' => 'ELDA.jpg'),
  array('name' => 'GENOVA ','images' => '','images_b' => ''),
  array('name' => 'GRECIA','images' => 'GRECIA.jpg','images_b' => 'GRECIA.jpg'),
  array('name' => 'SHAKIRA','images' => 'SHAKIRA.jpg','images_b' => 'SHAKIRA.jpg'),
  array('name' => 'FLORENCIA','images' => 'FLORENCIA.jpg','images_b' => 'FLORENCIA.jpg'),
  array('name' => 'NIZA','images' => 'NIZA.jpg','images_b' => 'NIZA.jpg'),
  array('name' => 'FONTANA','images' => 'FONTANA.jpg','images_b' => 'FONTANA.jpg'),
  array('name' => 'MADERA','images' => 'MADERA.jpg','images_b' => 'MADERA.jpg'),
  array('name' => 'KALIDA','images' => '','images_b' => ''),
  array('name' => 'CROMA','images' => 'CROMA.jpg,CROMA_1.jpg,CROMA_2.jpg','images_b' => 'CROMA.jpg,CROMA_1.jpg,CROMA_2.jpg'),
  array('name' => 'VOGUE','images' => 'VOGUE.jpg','images_b' => 'VOGUE.jpg'),
  array('name' => 'COSMOS','images' => '','images_b' => ''),
  array('name' => 'BOSTON','images' => 'BOSTON.jpg','images_b' => 'BOSTON.jpg'),
  array('name' => 'MULTICOLOR','images' => 'MULTICOLOR.jpg,MULTICOLOR_1.jpg,MULTICOLOR_2.jpg,MULTICOLOR_3.jpg,MULTICOLOR_4.jpg,MULTICOLOR_5.jpg','images_b' => 'MULTICOLOR.jpg,MULTICOLOR_1.jpg,MULTICOLOR_2.jpg,MULTICOLOR_3.jpg,MULTICOLOR_4.jpg,MULTICOLOR_5.jpg'),
  array('name' => 'EIDOS','images' => 'EIDOS.jpg,EIDOS_1.jpg,EIDOS_2.jpg,EIDOS_3.jpg,EIDOS_4.jpg','images_b' => 'EIDOS.jpg,EIDOS_1.jpg,EIDOS_2.jpg,EIDOS_3.jpg,EIDOS_4.jpg'),
  array('name' => 'MIX ','images' => '','images_b' => ''),
  array('name' => 'TURIN','images' => 'TURIN.jpg','images_b' => 'TURIN.jpg'),
  array('name' => 'CRISTAL','images' => 'CRISTAL.jpg','images_b' => 'CRISTAL.jpg'),
  array('name' => 'STICK','images' => 'STICK.jpg,STICK_1.jpg,STICK_2.jpg,STICK_3.jpg,STICK_4.jpg,STICK_5.jpg','images_b' => 'STICK.jpg,STICK_1.jpg,STICK_2.jpg,STICK_3.jpg,STICK_4.jpg,STICK_5.jpg'),
  array('name' => 'DECOR MILLENNIUM CONCEPT','images' => 'DECOR_MILLENNIUM_CONCEPT.jpg','images_b' => 'DECOR_MILLENNIUM_CONCEPT.jpg'),
  array('name' => 'VENICE','images' => 'VENICE.jpg,VENICE_1.jpg,VENICE_2.jpg,VENICE_3.jpg,VENICE_4.jpg','images_b' => 'VENICE.jpg,VENICE_1.jpg,VENICE_2.jpg,VENICE_3.jpg,VENICE_4.jpg'),
  array('name' => 'SPIRIT','images' => 'SPIRIT.jpg,SPIRIT_1.jpg','images_b' => 'SPIRIT.jpg,SPIRIT_1.jpg'),
  array('name' => 'TRAVERTINO','images' => 'TRAVERTINO.jpg,TRAVERTINO_1.jpg,TRAVERTINO_2.jpg,TRAVERTINO_3.jpg,TRAVERTINO_4.jpg,TRAVERTINO_5.jpg,TRAVERTINO_6.jpg,TRAVERTINO_7.jpg,TRAVERTINO_8.jpg,TRAVERTINO_9.jpg','images_b' => 'TRAVERTINO.jpg,TRAVERTINO_1.jpg,TRAVERTINO_2.jpg,TRAVERTINO_3.jpg,TRAVERTINO_4.jpg,TRAVERTINO_5.jpg,TRAVERTINO_6.jpg,TRAVERTINO_7.jpg,TRAVERTINO_8.jpg,TRAVERTINO_9.jpg'),
  array('name' => 'KALI','images' => 'KALI.jpg,KALI_1.jpg,KALI_2.jpg,KALI_3.jpg,KALI_4.jpg,KALI_5.jpg,KALI_6.jpg,KALI_7.jpg,KALI_8.jpg','images_b' => 'KALI.jpg,KALI_1.jpg,KALI_2.jpg,KALI_3.jpg,KALI_4.jpg,KALI_5.jpg,KALI_6.jpg,KALI_7.jpg,KALI_8.jpg'),
  array('name' => 'NEPAL','images' => 'NEPAL.jpg,NEPAL_1.jpg','images_b' => 'NEPAL.jpg,NEPAL_1.jpg'),
  array('name' => 'SAHARA','images' => 'SAHARA.jpg,SAHARA_1.jpg,SAHARA_2.jpg,SAHARA_3.jpg','images_b' => 'SAHARA.jpg,SAHARA_1.jpg,SAHARA_2.jpg,SAHARA_3.jpg'),
  array('name' => 'TRAVERTINO NOCE','images' => 'TRAVERTINO_NOCE.jpg','images_b' => 'TRAVERTINO_NOCE.jpg'),
  array('name' => 'TAIGA ','images' => '','images_b' => ''),
  array('name' => 'YAKARTA','images' => 'YAKARTA.jpg,YAKARTA_1.jpg,YAKARTA_2.jpg,YAKARTA_3.jpg','images_b' => 'YAKARTA.jpg,YAKARTA_1.jpg,YAKARTA_2.jpg,YAKARTA_3.jpg'),
  array('name' => 'GLASS','images' => 'GLASS.jpg','images_b' => 'GLASS.jpg'),
  array('name' => 'MARMOL','images' => '','images_b' => ''),
  array('name' => 'PAR-KER','images' => '','images_b' => ''),
  array('name' => 'JATOBA','images' => 'JATOBA.jpg','images_b' => 'JATOBA.jpg'),
  array('name' => 'STRADA','images' => 'STRADA.jpg','images_b' => 'STRADA.jpg'),
  array('name' => 'BRUNEI','images' => 'BRUNEI.jpg','images_b' => 'BRUNEI.jpg'),
  array('name' => 'SAIGON','images' => 'SAIGON.jpg','images_b' => 'SAIGON.jpg'),
  array('name' => 'FIRENZE ','images' => '','images_b' => ''),
  array('name' => 'BAMBU','images' => 'BAMBU.jpg,BAMBU_1.jpg,BAMBU_2.jpg,BAMBU_3.jpg,BAMBU_4.jpg,BAMBU_5.jpg','images_b' => 'BAMBU.jpg,BAMBU_1.jpg,BAMBU_2.jpg,BAMBU_3.jpg,BAMBU_4.jpg,BAMBU_5.jpg'),
  array('name' => 'ELECTRA','images' => 'ELECTRA.jpg,ELECTRA_1.jpg,ELECTRA_2.jpg,ELECTRA_3.jpg','images_b' => 'ELECTRA.jpg,ELECTRA_1.jpg,ELECTRA_2.jpg,ELECTRA_3.jpg'),
  array('name' => 'SHINE','images' => 'SHINE.jpg,SHINE_1.jpg,SHINE_2.jpg,SHINE_3.jpg','images_b' => 'SHINE.jpg,SHINE_1.jpg,SHINE_2.jpg,SHINE_3.jpg'),
  array('name' => 'FERROKER','images' => 'FERROKER.jpg,FERROKER_1.jpg,FERROKER_2.jpg','images_b' => 'FERROKER.jpg,FERROKER_1.jpg,FERROKER_2.jpg'),
  array('name' => 'RUGGINE ','images' => 'RUGGINE_.jpg','images_b' => 'RUGGINE_.jpg'),
  array('name' => 'LINE ','images' => '','images_b' => ''),
  array('name' => 'CLASSIC ','images' => '','images_b' => ''),
  array('name' => 'CAUCASO','images' => 'CAUCASO.jpg,CAUCASO_1.jpg','images_b' => 'CAUCASO.jpg,CAUCASO_1.jpg'),
  array('name' => 'IRONKER','images' => 'IRONKER.jpg,IRONKER_1.jpg,IRONKER_2.jpg,IRONKER_3.jpg','images_b' => 'IRONKER.jpg,IRONKER_1.jpg,IRONKER_2.jpg,IRONKER_3.jpg'),
  array('name' => 'VENEZIA','images' => 'VENEZIA.jpg,VENEZIA_1.jpg,VENEZIA_2.jpg,VENEZIA_3.jpg,VENEZIA_4.jpg,VENEZIA_5.jpg,VENEZIA_6.jpg,VENEZIA_7.jpg','images_b' => 'VENEZIA.jpg,VENEZIA_1.jpg,VENEZIA_2.jpg,VENEZIA_3.jpg,VENEZIA_4.jpg,VENEZIA_5.jpg,VENEZIA_6.jpg,VENEZIA_7.jpg'),
  array('name' => 'SILK','images' => 'SILK.jpg,SILK_1.jpg,SILK_2.jpg,SILK_3.jpg,SILK_4.jpg','images_b' => 'SILK.jpg,SILK_1.jpg,SILK_2.jpg,SILK_3.jpg,SILK_4.jpg'),
  array('name' => 'TISSUE','images' => '','images_b' => ''),
  array('name' => 'LEGNO','images' => 'LEGNO.jpg,LEGNO_1.jpg,LEGNO_2.jpg,LEGNO_3.jpg,LEGNO_4.jpg,LEGNO_5.jpg,LEGNO_6.jpg','images_b' => 'LEGNO.jpg,LEGNO_1.jpg,LEGNO_2.jpg,LEGNO_3.jpg,LEGNO_4.jpg,LEGNO_5.jpg,LEGNO_6.jpg'),
  array('name' => 'Atmosfere Veneziane (Damasco)','images' => 'Atmosfere_Veneziane_(Damasco).jpg,Atmosfere_Veneziane_(Damasco)_1.jpg,Atmosfere_Veneziane_(Damasco)_2.jpg,Atmosfere_Veneziane_(Damasco)_3.jpg','images_b' => 'Atmosfere_Veneziane_(Damasco).jpg,Atmosfere_Veneziane_(Damasco)_1.jpg,Atmosfere_Veneziane_(Damasco)_2.jpg,Atmosfere_Veneziane_(Damasco)_3.jpg'),
  array('name' => 'JABOT','images' => 'JABOT.jpg,JABOT_1.jpg,JABOT_2.jpg,JABOT_3.jpg','images_b' => 'JABOT.jpg,JABOT_1.jpg,JABOT_2.jpg,JABOT_3.jpg'),
  array('name' => 'Extasys','images' => 'Extasys.jpg,Extasys_1.jpg,Extasys_2.jpg,Extasys_3.jpg','images_b' => 'Extasys.jpg,Extasys_1.jpg,Extasys_2.jpg,Extasys_3.jpg'),
  array('name' => 'NICE','images' => 'NICE.jpg,NICE_1.jpg,NICE_2.jpg,NICE_3.jpg','images_b' => 'NICE.jpg,NICE_1.jpg,NICE_2.jpg,NICE_3.jpg'),
  array('name' => 'ARIS','images' => 'ARIS.jpg,ARIS_1.jpg','images_b' => 'ARIS.jpg,ARIS_1.jpg'),
  array('name' => 'VIVA','images' => 'VIVA.jpg,VIVA_1.jpg,VIVA_2.jpg','images_b' => 'VIVA.jpg,VIVA_1.jpg,VIVA_2.jpg'),
  array('name' => 'OLYMPO','images' => 'OLYMPO.jpg,OLYMPO_1.jpg,OLYMPO_2.jpg','images_b' => 'OLYMPO.jpg,OLYMPO_1.jpg,OLYMPO_2.jpg'),
  array('name' => 'ZEN 20x20','images' => 'ZEN_20x20.jpg','images_b' => 'ZEN_20x20.jpg'),
  array('name' => 'ATLANTIC','images' => 'ATLANTIC.jpg','images_b' => 'ATLANTIC.jpg'),
  array('name' => 'MAHON','images' => 'MAHON.jpg,MAHON_1.jpg,MAHON_2.jpg','images_b' => 'MAHON.jpg,MAHON_1.jpg,MAHON_2.jpg'),
  array('name' => 'ROSA','images' => 'ROSA.jpg','images_b' => 'ROSA.jpg'),
  array('name' => 'TAMIZA','images' => 'TAMIZA.jpg,TAMIZA_1.jpg,TAMIZA_2.jpg','images_b' => 'TAMIZA.jpg,TAMIZA_1.jpg,TAMIZA_2.jpg'),
  array('name' => 'DUO','images' => 'DUO.jpg','images_b' => 'DUO.jpg'),
  array('name' => 'FLORIS','images' => '','images_b' => ''),
  array('name' => 'LINEA','images' => 'LINEA.jpg','images_b' => 'LINEA.jpg'),
  array('name' => 'SAMARIA','images' => 'SAMARIA.jpg,SAMARIA_1.jpg','images_b' => 'SAMARIA.jpg,SAMARIA_1.jpg'),
  array('name' => 'FIDZI','images' => '','images_b' => ''),
  array('name' => 'KIRIBATI','images' => 'KIRIBATI.jpg','images_b' => 'KIRIBATI.jpg'),
  array('name' => 'RODOS','images' => '','images_b' => ''),
  array('name' => 'FIORINO','images' => 'FIORINO.jpg','images_b' => 'FIORINO.jpg'),
  array('name' => 'MADEIRA ','images' => '','images_b' => ''),
  array('name' => 'CASTANIO','images' => 'CASTANIO.jpg','images_b' => 'CASTANIO.jpg'),
  array('name' => 'KUBA','images' => 'KUBA.jpg,KUBA_1.jpg','images_b' => 'KUBA.jpg,KUBA_1.jpg'),
  array('name' => 'WERSAL','images' => 'WERSAL.jpg','images_b' => 'WERSAL.jpg'),
  array('name' => 'INVERNO','images' => 'INVERNO.jpg','images_b' => 'INVERNO.jpg'),
  array('name' => 'HOMME','images' => 'HOMME.jpg','images_b' => 'HOMME.jpg'),
  array('name' => 'HAWANA','images' => '','images_b' => ''),
  array('name' => 'ALBERO','images' => 'ALBERO.jpg','images_b' => 'ALBERO.jpg'),
  array('name' => 'TRAVERTINO','images' => 'TRAVERTINO.jpg,TRAVERTINO_1.jpg,TRAVERTINO_2.jpg,TRAVERTINO_3.jpg,TRAVERTINO_4.jpg,TRAVERTINO_5.jpg,TRAVERTINO_6.jpg,TRAVERTINO_7.jpg,TRAVERTINO_8.jpg,TRAVERTINO_9.jpg','images_b' => 'TRAVERTINO.jpg,TRAVERTINO_1.jpg,TRAVERTINO_2.jpg,TRAVERTINO_3.jpg,TRAVERTINO_4.jpg,TRAVERTINO_5.jpg,TRAVERTINO_6.jpg,TRAVERTINO_7.jpg,TRAVERTINO_8.jpg,TRAVERTINO_9.jpg'),
  array('name' => 'AMBER','images' => 'AMBER.jpg','images_b' => 'AMBER.jpg'),
  array('name' => 'SIROCCO','images' => 'SIROCCO.jpg','images_b' => 'SIROCCO.jpg'),
  array('name' => 'TAJGA','images' => 'TAJGA.jpg','images_b' => 'TAJGA.jpg'),
  array('name' => 'CALLE','images' => 'CALLE.jpg','images_b' => 'CALLE.jpg'),
  array('name' => 'HARION','images' => 'HARION.jpg','images_b' => 'HARION.jpg'),
  array('name' => 'ALABASTRINO','images' => 'ALABASTRINO.jpg','images_b' => 'ALABASTRINO.jpg'),
  array('name' => 'MAJOLIKA','images' => 'MAJOLIKA.jpg','images_b' => 'MAJOLIKA.jpg'),
  array('name' => 'IRIDIUM','images' => '','images_b' => ''),
  array('name' => 'TRAVERTINO','images' => 'TRAVERTINO.jpg,TRAVERTINO_1.jpg,TRAVERTINO_2.jpg,TRAVERTINO_3.jpg,TRAVERTINO_4.jpg,TRAVERTINO_5.jpg,TRAVERTINO_6.jpg,TRAVERTINO_7.jpg,TRAVERTINO_8.jpg,TRAVERTINO_9.jpg','images_b' => 'TRAVERTINO.jpg,TRAVERTINO_1.jpg,TRAVERTINO_2.jpg,TRAVERTINO_3.jpg,TRAVERTINO_4.jpg,TRAVERTINO_5.jpg,TRAVERTINO_6.jpg,TRAVERTINO_7.jpg,TRAVERTINO_8.jpg,TRAVERTINO_9.jpg'),
  array('name' => 'CUENCA','images' => 'CUENCA.jpg','images_b' => 'CUENCA.jpg'),
  array('name' => 'AVELLANA','images' => '','images_b' => ''),
  array('name' => 'CUERO','images' => 'CUERO.jpg','images_b' => 'CUERO.jpg'),
  array('name' => 'MANISES','images' => 'MANISES.jpg','images_b' => 'MANISES.jpg'),
  array('name' => 'LAGE','images' => 'LAGE.jpg','images_b' => 'LAGE.jpg'),
  array('name' => 'AGATHA','images' => 'AGATHA.jpg,AGATHA_1.jpg,AGATHA_2.jpg,AGATHA_3.jpg,AGATHA_4.jpg,AGATHA_5.jpg,AGATHA_6.jpg','images_b' => 'AGATHA.jpg,AGATHA_1.jpg,AGATHA_2.jpg,AGATHA_3.jpg,AGATHA_4.jpg,AGATHA_5.jpg,AGATHA_6.jpg'),
  array('name' => 'DOLMEN','images' => '','images_b' => ''),
  array('name' => 'TINTORETO','images' => 'TINTORETO.jpg','images_b' => 'TINTORETO.jpg'),
  array('name' => 'CROMO','images' => '','images_b' => ''),
  array('name' => 'FEEL','images' => 'FEEL.jpg','images_b' => 'FEEL.jpg'),
  array('name' => 'GEO','images' => 'GEO.jpg,GEO_1.jpg','images_b' => 'GEO.jpg,GEO_1.jpg'),
  array('name' => 'BOHEMIAN','images' => 'BOHEMIAN.jpg,BOHEMIAN_1.jpg,BOHEMIAN_2.jpg','images_b' => 'BOHEMIAN.jpg,BOHEMIAN_1.jpg,BOHEMIAN_2.jpg'),
  array('name' => 'DELHI ','images' => '','images_b' => ''),
  array('name' => 'ROMANZA','images' => 'ROMANZA.jpg','images_b' => 'ROMANZA.jpg'),
  array('name' => 'SPRING','images' => 'SPRING.jpg','images_b' => 'SPRING.jpg'),
  array('name' => 'GRAPHIC','images' => 'GRAPHIC.jpg','images_b' => 'GRAPHIC.jpg'),
  array('name' => 'MARACANA','images' => 'MARACANA.jpg','images_b' => 'MARACANA.jpg'),
  array('name' => 'CABARET','images' => 'CABARET.jpg','images_b' => 'CABARET.jpg'),
  array('name' => 'ORION','images' => 'ORION.jpg','images_b' => 'ORION.jpg'),
  array('name' => 'LYSANDER','images' => '','images_b' => ''),
  array('name' => 'ALCUDIA-VERONICA','images' => '','images_b' => ''),
  array('name' => 'CADIZ','images' => 'CADIZ.jpg,CADIZ_1.jpg,CADIZ_2.jpg','images_b' => 'CADIZ.jpg,CADIZ_1.jpg,CADIZ_2.jpg'),
  array('name' => 'CAMAS','images' => 'CAMAS.jpg','images_b' => 'CAMAS.jpg'),
  array('name' => 'HUELVA','images' => 'HUELVA.jpg','images_b' => 'HUELVA.jpg'),
  array('name' => 'ANDUJAR-AZAHARA ','images' => '','images_b' => ''),
  array('name' => 'CORDOBA-GRANADA-NERJA','images' => '','images_b' => ''),
  array('name' => 'SELLO DEL PASADO','images' => 'SELLO_DEL_PASADO.jpg,SELLO_DEL_PASADO_1.jpg','images_b' => 'SELLO_DEL_PASADO.jpg,SELLO_DEL_PASADO_1.jpg'),
  array('name' => '','images' => '','images_b' => ''),
  array('name' => 'Romance','images' => 'Romance.jpg,Romance_1.jpg','images_b' => 'Romance.jpg,Romance_1.jpg'),
  array('name' => 'Glamour','images' => 'Glamour.jpg','images_b' => 'Glamour.jpg'),
  array('name' => 'X-TILE','images' => '','images_b' => ''),
  array('name' => 'Oslo','images' => 'Oslo.jpg','images_b' => 'Oslo.jpg'),
  array('name' => 'GREDOS','images' => 'GREDOS.jpg','images_b' => 'GREDOS.jpg'),
  array('name' => 'PALOMA','images' => 'PALOMA.jpg,PALOMA_1.jpg,PALOMA_2.jpg','images_b' => 'PALOMA.jpg,PALOMA_1.jpg,PALOMA_2.jpg'),
  array('name' => 'Brujas','images' => 'Brujas.jpg','images_b' => 'Brujas.jpg'),
  array('name' => 'Terranova','images' => 'Terranova.jpg','images_b' => 'Terranova.jpg'),
  array('name' => 'Elba ','images' => '','images_b' => ''),
  array('name' => 'Kirov','images' => 'Kirov.jpg','images_b' => 'Kirov.jpg'),
  array('name' => 'Epica','images' => 'Epica.jpg,Epica_1.jpg','images_b' => 'Epica.jpg,Epica_1.jpg'),
  array('name' => 'Laminas','images' => 'Laminas.jpg,Laminas_1.jpg','images_b' => 'Laminas.jpg,Laminas_1.jpg'),
  array('name' => 'Bella Roma ','images' => '','images_b' => ''),
  array('name' => 'Bella Roma ','images' => '','images_b' => ''),
  array('name' => 'Tresor ','images' => '','images_b' => ''),
  array('name' => 'Ilusion','images' => 'Ilusion.jpg','images_b' => 'Ilusion.jpg'),
  array('name' => 'Lena','images' => 'Lena.jpg,Lena_1.jpg','images_b' => 'Lena.jpg,Lena_1.jpg'),
  array('name' => 'Romano','images' => 'Romano.jpg','images_b' => 'Romano.jpg'),
  array('name' => 'India_Bombay_Nepal_Tibet','images' => 'India_Bombay_Nepal_Tibet.jpg','images_b' => 'India_Bombay_Nepal_Tibet.jpg'),
  array('name' => 'Forest_Wood','images' => 'Forest_Wood.jpg,Forest_Wood_1.jpg','images_b' => 'Forest_Wood.jpg,Forest_Wood_1.jpg'),
  array('name' => 'Oregon','images' => 'Oregon.jpg','images_b' => 'Oregon.jpg'),
  array('name' => 'Sunshine','images' => 'Sunshine.jpg','images_b' => 'Sunshine.jpg'),
  array('name' => 'VIGO','images' => '','images_b' => ''),
  array('name' => 'TARIMA','images' => '','images_b' => ''),
  array('name' => 'BLOCK PAR-KER COLLECTION','images' => '','images_b' => ''),
  array('name' => 'TRIANA','images' => 'TRIANA.jpg','images_b' => 'TRIANA.jpg'),
  array('name' => 'EVOLUTION','images' => '','images_b' => ''),
  array('name' => 'CROSS','images' => '','images_b' => ''),
  array('name' => 'SERENA','images' => '','images_b' => ''),
  array('name' => 'RUSTICO','images' => '','images_b' => ''),
  array('name' => 'PIREO','images' => 'PIREO.jpg','images_b' => 'PIREO.jpg'),
  array('name' => 'ONIX','images' => 'ONIX.jpg,ONIX_1.jpg','images_b' => 'ONIX.jpg,ONIX_1.jpg'),
  array('name' => 'NAXOS','images' => 'NAXOS.jpg','images_b' => 'NAXOS.jpg'),
  array('name' => 'DELFOS','images' => 'DELFOS.jpg','images_b' => 'DELFOS.jpg'),
  array('name' => 'Euphoria','images' => 'Euphoria.jpg,Euphoria_1.jpg','images_b' => 'Euphoria.jpg,Euphoria_1.jpg'),
  array('name' => 'PORTO','images' => 'PORTO.jpg','images_b' => 'PORTO.jpg'),
  array('name' => 'STRATOS','images' => '','images_b' => ''),
  array('name' => 'AD','images' => 'AD.jpg,AD_1.jpg','images_b' => 'AD.jpg,AD_1.jpg'),
  array('name' => 'Fernstone','images' => 'Fernstone.jpg','images_b' => 'Fernstone.jpg'),
  array('name' => 'Ibiza','images' => 'Ibiza.jpg','images_b' => 'Ibiza.jpg'),
  array('name' => 'Aitana','images' => '','images_b' => ''),
  array('name' => 'Monti','images' => '','images_b' => ''),
  array('name' => 'Montblanc','images' => 'Montblanc.jpg','images_b' => 'Montblanc.jpg'),
  array('name' => 'Atlas','images' => 'Atlas.jpg','images_b' => 'Atlas.jpg'),
  array('name' => 'Everest','images' => '','images_b' => ''),
  array('name' => 'Ural','images' => 'Ural.jpg','images_b' => 'Ural.jpg'),
  array('name' => 'BOSTON','images' => 'BOSTON.jpg','images_b' => 'BOSTON.jpg'),
  array('name' => 'FLANDES','images' => 'FLANDES.jpg','images_b' => 'FLANDES.jpg'),
  array('name' => '','images' => '','images_b' => ''),
  array('name' => '400','images' => '400.jpg,400_1.jpg','images_b' => '400.jpg,400_1.jpg'),
  array('name' => '405','images' => '405.jpg','images_b' => '405.jpg'),
  array('name' => '409','images' => '409.jpg,409_1.jpg,409_2.jpg','images_b' => '409.jpg,409_1.jpg,409_2.jpg'),
  array('name' => '410','images' => '','images_b' => ''),
  array('name' => '418','images' => '418.jpg','images_b' => '418.jpg'),
  array('name' => '603','images' => '603.jpg','images_b' => '603.jpg'),
  array('name' => '567','images' => '567.jpg,567_1.jpg','images_b' => '567.jpg,567_1.jpg'),
  array('name' => '437','images' => '437.jpg','images_b' => '437.jpg'),
  array('name' => 'Zaffiri','images' => 'Zaffiri.jpg','images_b' => 'Zaffiri.jpg'),
  array('name' => 'Cervino','images' => '','images_b' => ''),
  array('name' => 'Stone Grigio','images' => '','images_b' => ''),
  array('name' => 'Stone Ferro','images' => '','images_b' => ''),
  array('name' => 'Pordoi','images' => '','images_b' => ''),
  array('name' => 'Work','images' => 'Work.jpg,Work_1.jpg,Work_2.jpg','images_b' => 'Work.jpg,Work_1.jpg,Work_2.jpg'),
  array('name' => 'Silverstone Blu','images' => 'Silverstone_Blu.jpg','images_b' => 'Silverstone_Blu.jpg'),
  array('name' => 'Silverstone Bruciato','images' => 'Silverstone_Bruciato.jpg','images_b' => 'Silverstone_Bruciato.jpg'),
  array('name' => 'Silverstone Moka','images' => 'Silverstone_Moka.jpg','images_b' => 'Silverstone_Moka.jpg'),
  array('name' => 'Silverstone Bianco','images' => 'Silverstone_Bianco.jpg','images_b' => 'Silverstone_Bianco.jpg'),
  array('name' => 'Montalcino Antico Scuro','images' => 'Montalcino_Antico_Scuro.jpg,Montalcino_Antico_Scuro_1.jpg','images_b' => 'Montalcino_Antico_Scuro.jpg,Montalcino_Antico_Scuro_1.jpg'),
  array('name' => 'Montalcino Arancio','images' => '','images_b' => ''),
  array('name' => 'Montalcino Giallo','images' => '','images_b' => ''),
  array('name' => 'Monterrey Bruciato','images' => 'Monterrey_Bruciato.jpg','images_b' => 'Monterrey_Bruciato.jpg'),
  array('name' => 'Yucatan Bruciato','images' => 'Yucatan_Bruciato.jpg','images_b' => 'Yucatan_Bruciato.jpg'),
  array('name' => 'SINE DIE','images' => 'SINE_DIE.jpg,SINE_DIE_1.jpg,SINE_DIE_2.jpg,SINE_DIE_3.jpg,SINE_DIE_4.jpg,SINE_DIE_5.jpg,SINE_DIE_6.jpg','images_b' => 'SINE_DIE.jpg,SINE_DIE_1.jpg,SINE_DIE_2.jpg,SINE_DIE_3.jpg,SINE_DIE_4.jpg,SINE_DIE_5.jpg,SINE_DIE_6.jpg'),
  array('name' => 'Alta Moda','images' => 'Alta_Moda.jpg','images_b' => 'Alta_Moda.jpg'),
  array('name' => 'DIAMOND','images' => 'DIAMOND.jpg','images_b' => 'DIAMOND.jpg'),
  array('name' => 'Metallica','images' => 'Metallica.jpg,Metallica_1.jpg,Metallica_2.jpg','images_b' => 'Metallica.jpg,Metallica_1.jpg,Metallica_2.jpg'),
  array('name' => 'Iride','images' => 'Iride.jpg','images_b' => 'Iride.jpg'),
  array('name' => 'Quartiere Latino','images' => 'Quartiere_Latino.jpg','images_b' => 'Quartiere_Latino.jpg'),
  array('name' => 'Stardust','images' => 'Stardust.jpg,Stardust_1.jpg','images_b' => 'Stardust.jpg,Stardust_1.jpg'),
  array('name' => 'De Origin','images' => 'De_Origin.jpg,De_Origin_1.jpg','images_b' => 'De_Origin.jpg,De_Origin_1.jpg'),
  array('name' => 'Luxor','images' => 'Luxor.jpg','images_b' => 'Luxor.jpg'),
  array('name' => 'MARES','images' => 'MARES.jpg,MARES_1.jpg,MARES_2.jpg','images_b' => 'MARES.jpg,MARES_1.jpg,MARES_2.jpg'),
  array('name' => 'MIERES','images' => 'MIERES.jpg','images_b' => 'MIERES.jpg'),
  array('name' => 'VIGO','images' => 'VIGO.jpg','images_b' => 'VIGO.jpg'),
  array('name' => 'SIENA','images' => '','images_b' => 'SIENA.jpg'),
  array('name' => 'TOLEDO','images' => '','images_b' => ''),
  array('name' => 'ELDA','images' => 'ELDA.jpg','images_b' => 'ELDA.jpg'),
  array('name' => 'GENOVA ','images' => '','images_b' => ''),
  array('name' => 'GRECIA','images' => 'GRECIA.jpg','images_b' => 'GRECIA.jpg'),
  array('name' => 'SHAKIRA','images' => 'SHAKIRA.jpg','images_b' => 'SHAKIRA.jpg'),
  array('name' => 'FLORENCIA','images' => 'FLORENCIA.jpg','images_b' => 'FLORENCIA.jpg'),
  array('name' => 'NIZA','images' => 'NIZA.jpg','images_b' => 'NIZA.jpg'),
  array('name' => 'FONTANA','images' => 'FONTANA.jpg','images_b' => 'FONTANA.jpg'),
  array('name' => 'TARIMA','images' => 'TARIMA.jpg','images_b' => 'TARIMA.jpg'),
  array('name' => 'MADERA','images' => 'MADERA.jpg','images_b' => 'MADERA.jpg'),
  array('name' => 'KALIDA','images' => 'KALIDA.jpg,KALIDA_1.jpg,KALIDA_2.jpg','images_b' => 'KALIDA.jpg,KALIDA_1.jpg,KALIDA_2.jpg'),
  array('name' => 'CROMA','images' => 'CROMA.jpg,CROMA_1.jpg,CROMA_2.jpg','images_b' => 'CROMA.jpg,CROMA_1.jpg,CROMA_2.jpg'),
  array('name' => 'VOGUE','images' => 'VOGUE.jpg','images_b' => 'VOGUE.jpg'),
  array('name' => 'IRIDIUM','images' => '','images_b' => ''),
  array('name' => 'COSMOS','images' => '','images_b' => ''),
  array('name' => 'BOSTON','images' => '','images_b' => ''),
  array('name' => 'MARMOL','images' => '','images_b' => ''),
  array('name' => 'BLOCK PAR-KER COLLECTION','images' => '','images_b' => ''),
  array('name' => 'CUENCA','images' => 'CUENCA.jpg','images_b' => 'CUENCA.jpg'),
  array('name' => 'MANISES','images' => 'MANISES.jpg','images_b' => 'MANISES.jpg'),
  array('name' => 'LAGE','images' => 'LAGE.jpg','images_b' => 'LAGE.jpg'),
  array('name' => 'DOLMEN','images' => 'DOLMEN.jpg,DOLMEN_1.jpg','images_b' => 'DOLMEN.jpg,DOLMEN_1.jpg'),
  array('name' => 'CROMO','images' => 'CROMO.jpg','images_b' => 'CROMO.jpg'),
  array('name' => 'LYSANDER','images' => 'LYSANDER.jpg','images_b' => 'LYSANDER.jpg'),
  array('name' => 'X-TILE','images' => '','images_b' => ''),
  array('name' => 'Oslo','images' => 'Oslo.jpg','images_b' => 'Oslo.jpg'),
  array('name' => 'GREDOS','images' => 'GREDOS.jpg','images_b' => 'GREDOS.jpg'),
  array('name' => 'Elba ','images' => '','images_b' => ''),
  array('name' => 'Kirov','images' => 'Kirov.jpg','images_b' => 'Kirov.jpg'),
  array('name' => 'Bella ROMA_','images' => 'Bella_ROMA_.jpg','images_b' => 'Bella_ROMA_.jpg'),
  array('name' => 'Forest_Wood','images' => 'Forest_Wood.jpg,Forest_Wood_1.jpg,Forest_Wood_2.jpg,Forest_Wood_3.jpg','images_b' => 'Forest_Wood.jpg,Forest_Wood_1.jpg,Forest_Wood_2.jpg,Forest_Wood_3.jpg'),
  array('name' => 'EVOLUTION','images' => 'EVOLUTION.jpg','images_b' => 'EVOLUTION.jpg'),
  array('name' => 'CROSS','images' => 'CROSS.jpg','images_b' => 'CROSS.jpg'),
  array('name' => 'SERENA','images' => 'SERENA.jpg','images_b' => 'SERENA.jpg'),
  array('name' => 'RUSTICO','images' => '','images_b' => ''),
  array('name' => 'NILO','images' => '','images_b' => ''),
  array('name' => 'ALCORA','images' => '','images_b' => ''),
  array('name' => 'AOSTA','images' => 'AOSTA.jpg','images_b' => 'AOSTA.jpg'),
  array('name' => 'TOSCANA','images' => 'TOSCANA.jpg','images_b' => 'TOSCANA.jpg'),
  array('name' => 'SEQUOIA','images' => 'SEQUOIA.jpg','images_b' => 'SEQUOIA.jpg'),
  array('name' => 'BYBLOS','images' => 'BYBLOS.jpg','images_b' => 'BYBLOS.jpg'),
  array('name' => 'MONTAGNE','images' => 'MONTAGNE.jpg','images_b' => 'MONTAGNE.jpg'),
  array('name' => 'TECTONIA','images' => 'TECTONIA.jpg','images_b' => 'TECTONIA.jpg'),
  array('name' => 'PETRIFIED FOREST','images' => 'PETRIFIED_FOREST.jpg','images_b' => 'PETRIFIED_FOREST.jpg'),
  array('name' => 'COLOSSOS','images' => 'COLOSSOS.jpg','images_b' => 'COLOSSOS.jpg'),
  array('name' => 'OLYMPUS','images' => 'OLYMPUS.jpg','images_b' => 'OLYMPUS.jpg'),
  array('name' => 'NUSS','images' => 'NUSS.jpg','images_b' => 'NUSS.jpg'),
  array('name' => 'NORWAY','images' => 'NORWAY.jpg,NORWAY_1.jpg','images_b' => 'NORWAY.jpg,NORWAY_1.jpg'),
  array('name' => 'ATALAYA','images' => '','images_b' => ''),
  array('name' => 'LUXE','images' => 'LUXE.jpg','images_b' => 'LUXE.jpg'),
  array('name' => 'DAMORE','images' => 'DAMORE.jpg','images_b' => 'DAMORE.jpg'),
  array('name' => 'DUCALE','images' => 'DUCALE.jpg','images_b' => 'DUCALE.jpg'),
  array('name' => 'IL SOGNO DELL ANGELO','images' => 'IL_SOGNO_DELL_ANGELO.jpg','images_b' => 'IL_SOGNO_DELL_ANGELO.jpg'),
  array('name' => 'Illusion','images' => '','images_b' => ''),
  array('name' => 'Natural GRESAN','images' => 'Natural_GRESAN.jpg,Natural_GRESAN_1.jpg,Natural_GRESAN_2.jpg,Natural_GRESAN_3.jpg,Natural_GRESAN_4.jpg,Natural_GRESAN_5.jpg,Natural_GRESAN_6.jpg,Natural_GRESAN_7.jpg,Natural_GRESAN_8.jpg,Natural_GRESAN_9.jpg','images_b' => 'Natural_GRESAN.jpg,Natural_GRESAN_1.jpg,Natural_GRESAN_2.jpg,Natural_GRESAN_3.jpg,Natural_GRESAN_4.jpg,Natural_GRESAN_5.jpg,Natural_GRESAN_6.jpg,Natural_GRESAN_7.jpg,Natural_GRESAN_8.jpg,Natural_GRESAN_9.jpg'),
  array('name' => 'NATUR','images' => 'NATUR.jpg,NATUR_1.jpg','images_b' => 'NATUR.jpg,NATUR_1.jpg'),
  array('name' => 'Cordoba','images' => 'Cordoba.jpg','images_b' => 'Cordoba.jpg'),
  array('name' => 'Penaroya','images' => 'Penaroya.jpg','images_b' => 'Penaroya.jpg'),
  array('name' => 'Ubeda','images' => 'Ubeda.jpg','images_b' => 'Ubeda.jpg'),
  array('name' => 'Hinojosa','images' => 'Hinojosa.jpg','images_b' => 'Hinojosa.jpg'),
  array('name' => 'Rociante','images' => '','images_b' => ''),
  array('name' => 'Romance','images' => 'Romance.jpg','images_b' => 'Romance.jpg'),
  array('name' => 'LAREDO','images' => 'LAREDO.jpg','images_b' => 'LAREDO.jpg'),
  array('name' => 'Monastir imperial','images' => 'Monastir_imperial.jpg','images_b' => 'Monastir_imperial.jpg'),
  array('name' => 'Forestal','images' => 'Forestal.jpg','images_b' => 'Forestal.jpg'),
  array('name' => 'Palace','images' => 'Palace.jpg','images_b' => 'Palace.jpg'),
  array('name' => 'Castano','images' => 'Castano.jpg','images_b' => 'Castano.jpg'),
  array('name' => 'Cerezo','images' => 'Cerezo.jpg','images_b' => 'Cerezo.jpg'),
  array('name' => 'Arce','images' => 'Arce.jpg','images_b' => 'Arce.jpg'),
  array('name' => 'Alamo','images' => 'Alamo.jpg','images_b' => 'Alamo.jpg'),
  array('name' => 'Quartz','images' => 'Quartz.jpg,Quartz_1.jpg','images_b' => 'Quartz.jpg,Quartz_1.jpg'),
  array('name' => 'Iberica','images' => 'Iberica.jpg','images_b' => 'Iberica.jpg'),
  array('name' => 'Oxide','images' => 'Oxide.jpg','images_b' => 'Oxide.jpg'),
  array('name' => 'Tropical Forest','images' => 'Tropical_Forest.jpg,Tropical_Forest_1.jpg','images_b' => 'Tropical_Forest.jpg,Tropical_Forest_1.jpg'),
  array('name' => 'Terra Di Siena Cotto','images' => '','images_b' => ''),
  array('name' => 'Terra Di Siena Cotto','images' => '','images_b' => ''),
  array('name' => 'Terra Di Siena Giallo','images' => '','images_b' => ''),
  array('name' => 'Terra Di Siena Giallo','images' => '','images_b' => ''),
  array('name' => 'Terra Di Siena Sabbia','images' => '','images_b' => ''),
  array('name' => 'Terra Di Siena Sabbia','images' => '','images_b' => ''),
  array('name' => 'Terra Di Siena Rosato','images' => '','images_b' => ''),
  array('name' => 'Terra Di Siena Rosato','images' => '','images_b' => ''),
  array('name' => 'Terra Di Siena Terra Scura','images' => '','images_b' => ''),
  array('name' => 'Terra Di Siena Terra Scura','images' => '','images_b' => ''),
  array('name' => 'Stratos','images' => 'Stratos.jpg','images_b' => 'Stratos.jpg'),
  array('name' => 'Iris Beige','images' => 'Iris_Beige.jpg','images_b' => 'Iris_Beige.jpg'),
  array('name' => 'Oda','images' => 'Oda.jpg,Oda_1.jpg','images_b' => 'Oda.jpg,Oda_1.jpg'),
  array('name' => 'Sarah','images' => 'Sarah.jpg','images_b' => 'Sarah.jpg'),
  array('name' => 'Siena','images' => 'Siena.jpg','images_b' => ''),
  array('name' => 'Aramis','images' => 'Aramis.jpg','images_b' => 'Aramis.jpg'),
  array('name' => 'Ghana','images' => 'Ghana.jpg','images_b' => 'Ghana.jpg'),
  array('name' => 'ASIA','images' => '','images_b' => ''),
  array('name' => 'Isla_Creta','images' => 'Isla_Creta.jpg,Isla_Creta_1.jpg,Isla_Creta_2.jpg','images_b' => 'Isla_Creta.jpg,Isla_Creta_1.jpg,Isla_Creta_2.jpg'),
  array('name' => 'Isla_Chipre','images' => 'Isla_Chipre.jpg','images_b' => 'Isla_Chipre.jpg'),
  array('name' => 'Mono','images' => 'Mono.jpg,Mono_1.jpg,Mono_2.jpg','images_b' => 'Mono.jpg,Mono_1.jpg,Mono_2.jpg'),
  array('name' => 'ZAMBIA','images' => 'ZAMBIA.jpg','images_b' => 'ZAMBIA.jpg'),
  array('name' => 'ORIGAMI','images' => 'ORIGAMI.jpg','images_b' => 'ORIGAMI.jpg'),
  array('name' => 'GRAFITE','images' => 'GRAFITE.jpg','images_b' => 'GRAFITE.jpg'),
  array('name' => 'DELICE','images' => 'DELICE.jpg','images_b' => 'DELICE.jpg'),
  array('name' => 'RUBRA','images' => 'RUBRA.jpg','images_b' => 'RUBRA.jpg'),
  array('name' => 'IDYLLA','images' => 'IDYLLA.jpg','images_b' => 'IDYLLA.jpg'),
  array('name' => 'CAFFETERIA','images' => 'CAFFETERIA.jpg','images_b' => 'CAFFETERIA.jpg'),
  array('name' => 'MORINGA','images' => 'MORINGA.jpg','images_b' => 'MORINGA.jpg'),
  array('name' => 'COLOUR','images' => 'COLOUR.jpg,COLOUR_1.jpg,COLOUR_2.jpg,COLOUR_3.jpg,COLOUR_4.jpg','images_b' => 'COLOUR.jpg,COLOUR_1.jpg,COLOUR_2.jpg,COLOUR_3.jpg,COLOUR_4.jpg'),
  array('name' => 'Bella Roma','images' => 'Bella_Roma.jpg,Bella_Roma_1.jpg','images_b' => 'Bella_Roma.jpg,Bella_Roma_1.jpg'),
  array('name' => 'Aracena','images' => 'Aracena.jpg,Aracena_1.jpg','images_b' => 'Aracena.jpg,Aracena_1.jpg'),
  array('name' => 'Corindon','images' => '','images_b' => ''),
  array('name' => 'Genova','images' => 'Genova.jpg,Genova_1.jpg','images_b' => 'Genova.jpg,Genova_1.jpg'),
  array('name' => 'Saten','images' => 'Saten.jpg','images_b' => 'Saten.jpg'),
  array('name' => 'Saten','images' => 'Saten.jpg','images_b' => 'Saten.jpg'),
  array('name' => 'ONIX GRESAN','images' => '','images_b' => ''),
  array('name' => 'NaturalGdB','images' => 'NaturalGdB.jpg,NaturalGdB_1.jpg,NaturalGdB_2.jpg,NaturalGdB_3.jpg','images_b' => 'NaturalGdB.jpg,NaturalGdB_1.jpg,NaturalGdB_2.jpg,NaturalGdB_3.jpg'),
  array('name' => 'BasaltoGdB','images' => 'BasaltoGdB.jpg','images_b' => 'BasaltoGdB.jpg'),
  array('name' => 'LavaGdB','images' => 'LavaGdB.jpg','images_b' => 'LavaGdB.jpg'),
  array('name' => 'Cadi Rustico Nar','images' => 'Cadi_Rustico_Nar.jpg,Cadi_Rustico_Nar_1.jpg','images_b' => 'Cadi_Rustico_Nar.jpg,Cadi_Rustico_Nar_1.jpg'),
  array('name' => 'Montserrat','images' => 'Montserrat.jpg,Montserrat_1.jpg','images_b' => 'Montserrat.jpg,Montserrat_1.jpg'),
  array('name' => 'INDIA NEPAL','images' => 'INDIA_NEPAL.jpg','images_b' => 'INDIA_NEPAL.jpg'),
  array('name' => 'MOTIVO','images' => 'MOTIVO.jpg','images_b' => 'MOTIVO.jpg'),
  array('name' => 'MADEIRA','images' => 'MADEIRA.jpg','images_b' => 'MADEIRA.jpg'),
  array('name' => 'CASCATA','images' => 'CASCATA.jpg','images_b' => 'CASCATA.jpg'),
  array('name' => 'BLANCO','images' => 'BLANCO.jpg','images_b' => 'BLANCO.jpg'),
  array('name' => 'BLANCO','images' => 'BLANCO.jpg','images_b' => 'BLANCO.jpg'),
  array('name' => 'Elba','images' => 'Elba.jpg','images_b' => 'Elba.jpg'),
  array('name' => 'Augusta','images' => 'Augusta.jpg','images_b' => 'Augusta.jpg'),
  array('name' => 'GRAND','images' => 'GRAND.jpg,GRAND_1.jpg','images_b' => 'GRAND.jpg,GRAND_1.jpg'),
  array('name' => 'Glamour Champagne','images' => 'Glamour_Champagne.jpg','images_b' => 'Glamour_Champagne.jpg'),
  array('name' => 'Glamour ROSE','images' => 'Glamour_ROSE.jpg','images_b' => 'Glamour_ROSE.jpg'),
  array('name' => 'Aitana_Monti','images' => 'Aitana_Monti.jpg','images_b' => 'Aitana_Monti.jpg'),
  array('name' => 'Oset Atlas','images' => 'Oset_Atlas.jpg','images_b' => 'Oset_Atlas.jpg'),
  array('name' => 'OSET ONIX','images' => 'OSET_ONIX.jpg','images_b' => 'OSET_ONIX.jpg'),
  array('name' => '','images' => '','images_b' => ''),
  array('name' => 'AGATHA FUCSIA','images' => 'AGATHA_FUCSIA.jpg','images_b' => 'AGATHA_FUCSIA.jpg'),
  array('name' => 'Oslo','images' => 'Oslo.jpg','images_b' => 'Oslo.jpg'),
  array('name' => 'GREDOS','images' => 'GREDOS.jpg','images_b' => 'GREDOS.jpg'),
  array('name' => 'PALOMA','images' => 'PALOMA.jpg,PALOMA_1.jpg,PALOMA_2.jpg','images_b' => 'PALOMA.jpg,PALOMA_1.jpg,PALOMA_2.jpg'),
  array('name' => 'Brujas','images' => 'Brujas.jpg','images_b' => 'Brujas.jpg'),
  array('name' => 'Laminas_Corindon','images' => 'Laminas_Corindon.jpg,Laminas_Corindon_1.jpg,Laminas_Corindon_2.jpg,Laminas_Corindon_3.jpg','images_b' => 'Laminas_Corindon.jpg,Laminas_Corindon_1.jpg,Laminas_Corindon_2.jpg,Laminas_Corindon_3.jpg'),
  array('name' => 'NILO','images' => '','images_b' => ''),
  array('name' => 'AGATHA 25x50','images' => 'AGATHA_25x50.jpg,AGATHA_25x50_1.jpg,AGATHA_25x50_2.jpg','images_b' => 'AGATHA_25x50.jpg,AGATHA_25x50_1.jpg,AGATHA_25x50_2.jpg'),
  array('name' => 'BOSTON PLAZA','images' => 'BOSTON_PLAZA.jpg','images_b' => 'BOSTON_PLAZA.jpg'),
  array('name' => 'Montalcino','images' => 'Montalcino.jpg','images_b' => 'Montalcino.jpg'),
  array('name' => 'Travertino it','images' => 'Travertino_it.jpg,Travertino_it_1.jpg','images_b' => 'Travertino_it.jpg,Travertino_it_1.jpg'),
  array('name' => 'TAIGA PORCELANOSA','images' => 'TAIGA_PORCELANOSA.jpg','images_b' => 'TAIGA_PORCELANOSA.jpg'),
  array('name' => 'TRAVERTINO pl','images' => 'TRAVERTINO_pl.jpg','images_b' => 'TRAVERTINO_pl.jpg'),
  array('name' => 'ALCORA','images' => 'ALCORA.jpg','images_b' => 'ALCORA.jpg'),
  array('name' => 'Terra Di Siena','images' => 'Terra_Di_Siena.jpg,Terra_Di_Siena_1.jpg,Terra_Di_Siena_2.jpg,Terra_Di_Siena_3.jpg,Terra_Di_Siena_4.jpg','images_b' => 'Terra_Di_Siena.jpg,Terra_Di_Siena_1.jpg,Terra_Di_Siena_2.jpg,Terra_Di_Siena_3.jpg,Terra_Di_Siena_4.jpg'),
  array('name' => 'Terra_Di_Siena','images' => 'Terra_Di_Siena.jpg,Terra_Di_Siena_1.jpg,Terra_Di_Siena_2.jpg,Terra_Di_Siena_3.jpg,Terra_Di_Siena_4.jpg','images_b' => 'Terra_Di_Siena.jpg,Terra_Di_Siena_1.jpg,Terra_Di_Siena_2.jpg,Terra_Di_Siena_3.jpg,Terra_Di_Siena_4.jpg'),
  array('name' => 'Terra Di Siena_','images' => 'Terra_Di_Siena_.jpg,Terra_Di_Siena__1.jpg','images_b' => 'Terra_Di_Siena_.jpg,Terra_Di_Siena__1.jpg'),
  array('name' => 'Terra Di Siena_','images' => 'Terra_Di_Siena_.jpg,Terra_Di_Siena__1.jpg','images_b' => 'Terra_Di_Siena_.jpg,Terra_Di_Siena__1.jpg'),
  array('name' => 'Megara','images' => 'Megara.jpg','images_b' => 'Megara.jpg'),
  array('name' => 'Africa','images' => 'Africa.jpg','images_b' => 'Africa.jpg'),
  array('name' => 'DUNE','images' => 'DUNE.jpg,DUNE_1.jpg','images_b' => 'DUNE.jpg,DUNE_1.jpg'),
  array('name' => 'Alhambra','images' => 'Alhambra.jpg','images_b' => 'Alhambra.jpg'),
  array('name' => 'Majestic','images' => 'Majestic.jpg','images_b' => 'Majestic.jpg'),
  array('name' => 'ALHAMBRA PLAZA','images' => 'ALHAMBRA_PLAZA.jpg','images_b' => 'ALHAMBRA_PLAZA.jpg'),
  array('name' => 'Agadir','images' => 'Agadir.jpg,Agadir_1.jpg','images_b' => ''),
  array('name' => 'Terra DiSiena','images' => 'Terra_DiSiena.jpg,Terra_DiSiena_1.jpg','images_b' => 'Terra_DiSiena.jpg,Terra_DiSiena_1.jpg'),
  array('name' => 'VOGUE FANAL','images' => 'VOGUE_FANAL.jpg','images_b' => 'VOGUE_FANAL.jpg'),
  array('name' => 'DELHI','images' => 'DELHI.jpg,DELHI_1.jpg','images_b' => 'DELHI.jpg,DELHI_1.jpg'),
  array('name' => 'VOGUE','images' => 'VOGUE.jpg','images_b' => 'VOGUE.jpg'),
  array('name' => 'EMPERADOR','images' => 'EMPERADOR.jpg','images_b' => 'EMPERADOR.jpg'),
  array('name' => 'ANDUJAR-AZAHARA','images' => '','images_b' => ''),
  array('name' => 'ART','images' => 'ART.jpg','images_b' => 'ART.jpg'),
  array('name' => 'Blestki','images' => 'Blestki.jpg','images_b' => 'Blestki.jpg'),
  array('name' => 'MIXes 15x15','images' => 'MIXes_15x15.jpg','images_b' => 'MIXes_15x15.jpg'),
  array('name' => 'MIXes','images' => 'MIXes.jpg','images_b' => 'MIXes.jpg'),
  array('name' => 'MIXes 23x48','images' => 'MIXes_23x48.jpg','images_b' => 'MIXes_23x48.jpg'),
  array('name' => 'Blestki MIX','images' => 'Blestki_MIX.jpg','images_b' => 'Blestki_MIX.jpg'),
  array('name' => 'Kameshki','images' => 'Kameshki.jpg','images_b' => 'Kameshki.jpg'),
  array('name' => 'SKOL','images' => 'SKOL.jpg','images_b' => 'SKOL.jpg'),
  array('name' => 'ANDUJAR AZAHARA ','images' => '','images_b' => ''),
  array('name' => 'ANDUJAR_AZAHARA','images' => 'ANDUJAR_AZAHARA.jpg,ANDUJAR_AZAHARA_1.jpg,ANDUJAR_AZAHARA_2.jpg,ANDUJAR_AZAHARA_3.jpg','images_b' => 'ANDUJAR_AZAHARA.jpg,ANDUJAR_AZAHARA_1.jpg,ANDUJAR_AZAHARA_2.jpg,ANDUJAR_AZAHARA_3.jpg'),
  array('name' => 'CORDOBA_GRANADA_NERJA','images' => 'CORDOBA_GRANADA_NERJA.jpg,CORDOBA_GRANADA_NERJA_1.jpg,CORDOBA_GRANADA_NERJA_2.jpg','images_b' => 'CORDOBA_GRANADA_NERJA.jpg,CORDOBA_GRANADA_NERJA_1.jpg,CORDOBA_GRANADA_NERJA_2.jpg'),
  array('name' => 'ALCUDIA VERONICA','images' => 'ALCUDIA_VERONICA.jpg,ALCUDIA_VERONICA_1.jpg','images_b' => 'ALCUDIA_VERONICA.jpg,ALCUDIA_VERONICA_1.jpg'),
  array('name' => 'Navona Rosa','images' => 'Navona_Rosa.jpg,Navona_Rosa_1.jpg','images_b' => 'Navona_Rosa.jpg,Navona_Rosa_1.jpg'),
  array('name' => 'Feldhaus Klinker ','images' => 'Feldhaus_Klinker_.jpg,Feldhaus_Klinker__1.jpg,Feldhaus_Klinker__2.jpg','images_b' => 'Feldhaus_Klinker_.jpg'),
  array('name' => 'Stroeher','images' => 'Stroeher.jpg,Stroeher_1.jpg','images_b' => 'Stroeher.jpg'),
  array('name' => 'Feldhaus Klinker  ','images' => 'Feldhaus_Klinker__.jpg,Feldhaus_Klinker___1.jpg,Feldhaus_Klinker___2.jpg','images_b' => 'Feldhaus_Klinker__.jpg'),
  array('name' => 'KORZILIUS','images' => 'KORZILIUS.jpg','images_b' => 'KORZILIUS.jpg'),
  array('name' => 'Stroeher 15x30','images' => 'Stroeher_15x30.jpg,Stroeher_15x30_1.jpg,Stroeher_15x30_2.jpg,Stroeher_15x30_3.jpg,Stroeher_15x30_4.jpg,Stroeher_15x30_5.jpg','images_b' => 'Stroeher_15x30.jpg,Stroeher_15x30_1.jpg,Stroeher_15x30_2.jpg,Stroeher_15x30_3.jpg'),
  array('name' => 'Stone Grigio_Ferro','images' => '','images_b' => ''),
  array('name' => 'Helsinki Beige_Naranija','images' => 'Helsinki_Beige_Naranija.jpg,Helsinki_Beige_Naranija_1.jpg,Helsinki_Beige_Naranija_2.jpg','images_b' => 'Helsinki_Beige_Naranija.jpg,Helsinki_Beige_Naranija_1.jpg,Helsinki_Beige_Naranija_2.jpg'),
  array('name' => 'Helsinki Blanco_Pistacho','images' => 'Helsinki_Blanco_Pistacho.jpg','images_b' => 'Helsinki_Blanco_Pistacho.jpg'),
  array('name' => 'Shine Grespania','images' => 'Shine_Grespania.jpg,Shine_Grespania_1.jpg','images_b' => 'Shine_Grespania.jpg,Shine_Grespania_1.jpg'),
  array('name' => 'GENOVA','images' => 'GENOVA.jpg','images_b' => 'GENOVA.jpg'),
  array('name' => 'BOSTON PORCELANOSA','images' => '','images_b' => ''),
  array('name' => 'LEGNO','images' => 'LEGNO.jpg,LEGNO_1.jpg,LEGNO_2.jpg,LEGNO_3.jpg,LEGNO_4.jpg,LEGNO_5.jpg,LEGNO_6.jpg','images_b' => 'LEGNO.jpg,LEGNO_1.jpg,LEGNO_2.jpg,LEGNO_3.jpg,LEGNO_4.jpg,LEGNO_5.jpg,LEGNO_6.jpg'),
  array('name' => 'AVELLANA CUERO','images' => 'AVELLANA_CUERO.jpg','images_b' => 'AVELLANA_CUERO.jpg'),
  array('name' => 'ZEUS','images' => 'ZEUS.jpg,ZEUS_1.jpg,ZEUS_2.jpg,ZEUS_3.jpg,ZEUS_4.jpg,ZEUS_5.jpg','images_b' => 'ZEUS.jpg,ZEUS_1.jpg,ZEUS_2.jpg,ZEUS_3.jpg,ZEUS_4.jpg,ZEUS_5.jpg'),
  array('name' => 'Urbe','images' => '','images_b' => ''),
  array('name' => 'Guadiato','images' => '','images_b' => ''),
  array('name' => 'OSLO PLAZA','images' => 'OSLO_PLAZA.jpg','images_b' => 'OSLO_PLAZA.jpg'),
  array('name' => 'ZEUS','images' => '','images_b' => ''),
  array('name' => 'RAK CERAMICS 30x60','images' => 'RAK_CERAMICS_30x60.jpg,RAK_CERAMICS_30x60_1.jpg,RAK_CERAMICS_30x60_2.jpg','images_b' => 'RAK_CERAMICS_30x60.jpg,RAK_CERAMICS_30x60_1.jpg,RAK_CERAMICS_30x60_2.jpg'),
  array('name' => 'RAK CERAMICS 45x45','images' => 'RAK_CERAMICS_45x45.jpg,RAK_CERAMICS_45x45_1.jpg,RAK_CERAMICS_45x45_2.jpg','images_b' => 'RAK_CERAMICS_45x45.jpg,RAK_CERAMICS_45x45_1.jpg,RAK_CERAMICS_45x45_2.jpg'),
  array('name' => 'RAK CERAMICS 40x40','images' => 'RAK_CERAMICS_40x40.jpg,RAK_CERAMICS_40x40_1.jpg,RAK_CERAMICS_40x40_2.jpg,RAK_CERAMICS_40x40_3.jpg,RAK_CERAMICS_40x40_4.jpg,RAK_CERAMICS_40x40_5.jpg','images_b' => 'RAK_CERAMICS_40x40.jpg,RAK_CERAMICS_40x40_1.jpg,RAK_CERAMICS_40x40_2.jpg,RAK_CERAMICS_40x40_3.jpg,RAK_CERAMICS_40x40_4.jpg,RAK_CERAMICS_40x40_5.jpg'),
  array('name' => 'Tiffany Plaza','images' => 'Tiffany_Plaza.jpg','images_b' => 'Tiffany_Plaza.jpg'),
  array('name' => 'STRATUS RUSTICO','images' => 'STRATUS_RUSTICO.jpg,STRATUS_RUSTICO_1.jpg,STRATUS_RUSTICO_2.jpg','images_b' => 'STRATUS_RUSTICO.jpg,STRATUS_RUSTICO_1.jpg,STRATUS_RUSTICO_2.jpg'),
  array('name' => 'Dix Ares','images' => 'Dix_Ares.jpg,Dix_Ares_1.jpg','images_b' => 'Dix_Ares.jpg,Dix_Ares_1.jpg'),
  array('name' => 'SALTILLO','images' => 'SALTILLO.jpg','images_b' => 'SALTILLO.jpg'),
  array('name' => 'DAKAR','images' => 'DAKAR.jpg,DAKAR_1.jpg,DAKAR_2.jpg,DAKAR_3.jpg,DAKAR_4.jpg,DAKAR_5.jpg','images_b' => 'DAKAR.jpg,DAKAR_1.jpg,DAKAR_2.jpg,DAKAR_3.jpg,DAKAR_4.jpg,DAKAR_5.jpg'),
  array('name' => 'DAKAR','images' => 'DAKAR.jpg,DAKAR_1.jpg,DAKAR_2.jpg,DAKAR_3.jpg,DAKAR_4.jpg,DAKAR_5.jpg','images_b' => 'DAKAR.jpg,DAKAR_1.jpg,DAKAR_2.jpg,DAKAR_3.jpg,DAKAR_4.jpg,DAKAR_5.jpg'),
  array('name' => 'FANTASIA','images' => 'FANTASIA.jpg,FANTASIA_1.jpg','images_b' => 'FANTASIA.jpg,FANTASIA_1.jpg'),
  array('name' => 'BOMBAI','images' => 'BOMBAI.jpg,BOMBAI_1.jpg','images_b' => 'BOMBAI.jpg,BOMBAI_1.jpg'),
  array('name' => 'LUXOR (Metallizado)','images' => 'LUXOR_(Metallizado).jpg,LUXOR_(Metallizado)_1.jpg,LUXOR_(Metallizado)_2.jpg,LUXOR_(Metallizado)_3.jpg','images_b' => 'LUXOR_(Metallizado).jpg,LUXOR_(Metallizado)_1.jpg,LUXOR_(Metallizado)_2.jpg,LUXOR_(Metallizado)_3.jpg'),
  array('name' => 'ELBA Beige','images' => 'ELBA_Beige.jpg,ELBA_Beige_1.jpg','images_b' => 'ELBA_Beige.jpg,ELBA_Beige_1.jpg'),
  array('name' => 'ELBA Nogal','images' => 'ELBA_Nogal.jpg,ELBA_Nogal_1.jpg','images_b' => 'ELBA_Nogal.jpg,ELBA_Nogal_1.jpg'),
  array('name' => 'CALACATTA','images' => 'CALACATTA.jpg,CALACATTA_1.jpg','images_b' => 'CALACATTA.jpg,CALACATTA_1.jpg'),
  array('name' => 'IRINA','images' => 'IRINA.jpg,IRINA_1.jpg,IRINA_2.jpg,IRINA_3.jpg','images_b' => 'IRINA.jpg,IRINA_1.jpg,IRINA_2.jpg,IRINA_3.jpg'),
  array('name' => 'TOLEDO','images' => '','images_b' => ''),
  array('name' => 'TOLEDO_','images' => 'TOLEDO_.jpg,TOLEDO__1.jpg,TOLEDO__2.jpg,TOLEDO__3.jpg,TOLEDO__4.jpg','images_b' => 'TOLEDO_.jpg,TOLEDO__1.jpg,TOLEDO__2.jpg,TOLEDO__3.jpg,TOLEDO__4.jpg'),
  array('name' => 'CADIZ','images' => 'CADIZ.jpg,CADIZ_1.jpg,CADIZ_2.jpg','images_b' => 'CADIZ.jpg,CADIZ_1.jpg,CADIZ_2.jpg'),
  array('name' => 'BELMEZ-ROJO VILLANUEVA','images' => '','images_b' => ''),
  array('name' => 'NAVARRA-EBRO-TURIA','images' => '','images_b' => ''),
  array('name' => 'ARIS_','images' => 'ARIS_.jpg','images_b' => 'ARIS_.jpg'),
  array('name' => 'BALMA','images' => 'BALMA.jpg,BALMA_1.jpg','images_b' => 'BALMA.jpg,BALMA_1.jpg'),
  array('name' => 'DIAMOND (Metallizado)','images' => 'DIAMOND_(Metallizado).jpg','images_b' => 'DIAMOND_(Metallizado).jpg'),
  array('name' => 'GREDOS_','images' => 'GREDOS_.jpg,GREDOS__1.jpg,GREDOS__2.jpg','images_b' => 'GREDOS_.jpg,GREDOS__1.jpg,GREDOS__2.jpg'),
  array('name' => 'ORSAY','images' => 'ORSAY.jpg','images_b' => 'ORSAY.jpg'),
  array('name' => 'BAHIA','images' => 'BAHIA.jpg','images_b' => 'BAHIA.jpg'),
  array('name' => 'BELMEZ ROJO VILLANUEVA','images' => 'BELMEZ_ROJO_VILLANUEVA.jpg,BELMEZ_ROJO_VILLANUEVA_1.jpg,BELMEZ_ROJO_VILLANUEVA_2.jpg','images_b' => 'BELMEZ_ROJO_VILLANUEVA.jpg,BELMEZ_ROJO_VILLANUEVA_1.jpg,BELMEZ_ROJO_VILLANUEVA_2.jpg'),
  array('name' => 'NAVARRA EBRO TURIA','images' => 'NAVARRA_EBRO_TURIA.jpg','images_b' => 'NAVARRA_EBRO_TURIA.jpg'),
  array('name' => 'CADIZ_','images' => 'CADIZ_.jpg','images_b' => 'CADIZ_.jpg'),
  array('name' => 'CARRARA','images' => 'CARRARA.jpg,CARRARA_1.jpg','images_b' => 'CARRARA.jpg,CARRARA_1.jpg'),
  array('name' => 'EVOLUTION (Metallizado)','images' => 'EVOLUTION_(Metallizado).jpg,EVOLUTION_(Metallizado)_1.jpg,EVOLUTION_(Metallizado)_2.jpg','images_b' => 'EVOLUTION_(Metallizado).jpg,EVOLUTION_(Metallizado)_1.jpg,EVOLUTION_(Metallizado)_2.jpg'),
  array('name' => 'ONDAS','images' => 'ONDAS.jpg,ONDAS_1.jpg,ONDAS_2.jpg','images_b' => 'ONDAS.jpg,ONDAS_1.jpg,ONDAS_2.jpg'),
  array('name' => 'RAK CERAMICS 60x60','images' => 'RAK_CERAMICS_60x60.jpg,RAK_CERAMICS_60x60_1.jpg,RAK_CERAMICS_60x60_2.jpg,RAK_CERAMICS_60x60_3.jpg,RAK_CERAMICS_60x60_4.jpg','images_b' => 'RAK_CERAMICS_60x60.jpg,RAK_CERAMICS_60x60_1.jpg,RAK_CERAMICS_60x60_2.jpg,RAK_CERAMICS_60x60_3.jpg,RAK_CERAMICS_60x60_4.jpg'),
  array('name' => 'INDIA','images' => 'INDIA.jpg','images_b' => 'INDIA.jpg'),
  array('name' => 'RAK CERAMICS 60x90','images' => 'RAK_CERAMICS_60x90.jpg','images_b' => 'RAK_CERAMICS_60x90.jpg'),
  array('name' => 'RAK MOSAIC','images' => 'RAK_MOSAIC.jpg,RAK_MOSAIC_1.jpg,RAK_MOSAIC_2.jpg,RAK_MOSAIC_3.jpg,RAK_MOSAIC_4.jpg,RAK_MOSAIC_5.jpg,RAK_MOSAIC_6.jpg,RAK_MOSAIC_7.jpg,RAK_MOSAIC_8.jpg','images_b' => 'RAK_MOSAIC.jpg,RAK_MOSAIC_1.jpg,RAK_MOSAIC_2.jpg,RAK_MOSAIC_3.jpg,RAK_MOSAIC_4.jpg,RAK_MOSAIC_5.jpg,RAK_MOSAIC_6.jpg,RAK_MOSAIC_7.jpg,RAK_MOSAIC_8.jpg'),
  array('name' => 'RAK CERAMICS STEPS','images' => 'RAK_CERAMICS_STEPS.jpg,RAK_CERAMICS_STEPS_1.jpg,RAK_CERAMICS_STEPS_2.jpg,RAK_CERAMICS_STEPS_3.jpg,RAK_CERAMICS_STEPS_4.jpg','images_b' => 'RAK_CERAMICS_STEPS.jpg,RAK_CERAMICS_STEPS_1.jpg,RAK_CERAMICS_STEPS_2.jpg,RAK_CERAMICS_STEPS_3.jpg,RAK_CERAMICS_STEPS_4.jpg'),
  array('name' => 'RAK CERAMICS','images' => '','images_b' => ''),
  array('name' => 'CORDOBA_','images' => 'CORDOBA_.jpg','images_b' => 'CORDOBA_.jpg'),
  array('name' => 'AROA_','images' => 'AROA_.jpg,AROA__1.jpg','images_b' => 'AROA_.jpg,AROA__1.jpg'),
  array('name' => 'Anadolu','images' => 'Anadolu.jpg,Anadolu_1.jpg,Anadolu_2.jpg','images_b' => 'Anadolu.jpg,Anadolu_1.jpg,Anadolu_2.jpg'),
  array('name' => 'MARES_','images' => 'MARES_.jpg','images_b' => 'MARES_.jpg'),
  array('name' => 'MIX','images' => 'MIX.jpg','images_b' => 'MIX.jpg'),
  array('name' => 'TOKIO','images' => 'TOKIO.jpg','images_b' => 'TOKIO.jpg'),
  array('name' => 'FIRENZE','images' => 'FIRENZE.jpg','images_b' => 'FIRENZE.jpg'),
  array('name' => 'MORELLA','images' => 'MORELLA.jpg,MORELLA_1.jpg','images_b' => 'MORELLA.jpg,MORELLA_1.jpg'),
  array('name' => 'RIOJA','images' => 'RIOJA.jpg,RIOJA_1.jpg','images_b' => 'RIOJA.jpg,RIOJA_1.jpg'),
  array('name' => '906','images' => '906.jpg','images_b' => '906.jpg'),
  array('name' => '7000','images' => '7000.jpg','images_b' => '7000.jpg'),
  array('name' => 'QATAR','images' => 'QATAR.jpg','images_b' => 'QATAR.jpg'),
  array('name' => 'MARMORIS','images' => 'MARMORIS.jpg,MARMORIS_1.jpg,MARMORIS_2.jpg','images_b' => 'MARMORIS.jpg,MARMORIS_1.jpg,MARMORIS_2.jpg'),
  array('name' => 'METAL STYLE','images' => 'METAL_STYLE.jpg,METAL_STYLE_1.jpg,METAL_STYLE_2.jpg','images_b' => 'METAL_STYLE.jpg,METAL_STYLE_1.jpg,METAL_STYLE_2.jpg'),
  array('name' => 'GEOLOGY','images' => 'GEOLOGY.jpg,GEOLOGY_1.jpg,GEOLOGY_2.jpg,GEOLOGY_3.jpg','images_b' => 'GEOLOGY.jpg,GEOLOGY_1.jpg,GEOLOGY_2.jpg,GEOLOGY_3.jpg'),
  array('name' => 'IMAGO','images' => 'IMAGO.jpg,IMAGO_1.jpg,IMAGO_2.jpg','images_b' => 'IMAGO.jpg,IMAGO_1.jpg,IMAGO_2.jpg'),
  array('name' => 'FIFTH AVENUE','images' => 'FIFTH_AVENUE.jpg,FIFTH_AVENUE_1.jpg,FIFTH_AVENUE_2.jpg,FIFTH_AVENUE_3.jpg,FIFTH_AVENUE_4.jpg,FIFTH_AVENUE_5.jpg','images_b' => 'FIFTH_AVENUE.jpg,FIFTH_AVENUE_1.jpg,FIFTH_AVENUE_2.jpg,FIFTH_AVENUE_3.jpg,FIFTH_AVENUE_4.jpg,FIFTH_AVENUE_5.jpg'),
  array('name' => 'MEZZO','images' => 'MEZZO.jpg','images_b' => 'MEZZO.jpg'),
  array('name' => 'MONACO','images' => 'MONACO.jpg','images_b' => 'MONACO.jpg'),
  array('name' => 'IMPERIAL','images' => 'IMPERIAL.jpg,IMPERIAL_1.jpg','images_b' => 'IMPERIAL.jpg,IMPERIAL_1.jpg'),
  array('name' => 'GLITTER','images' => 'GLITTER.jpg','images_b' => 'GLITTER.jpg'),
  array('name' => 'JUPITER','images' => 'JUPITER.jpg','images_b' => 'JUPITER.jpg'),
  array('name' => 'ROSAGRES','images' => '','images_b' => ''),
  array('name' => 'GROOVE','images' => 'GROOVE.jpg,GROOVE_1.jpg,GROOVE_2.jpg,GROOVE_3.jpg','images_b' => 'GROOVE.jpg,GROOVE_1.jpg,GROOVE_2.jpg,GROOVE_3.jpg'),
  array('name' => 'LIFE FAP','images' => 'LIFE_FAP.jpg,LIFE_FAP_1.jpg,LIFE_FAP_2.jpg,LIFE_FAP_3.jpg','images_b' => 'LIFE_FAP.jpg,LIFE_FAP_1.jpg,LIFE_FAP_2.jpg,LIFE_FAP_3.jpg'),
  array('name' => 'MADERAs','images' => 'MADERAs.jpg,MADERAs_1.jpg','images_b' => 'MADERAs.jpg,MADERAs_1.jpg'),
  array('name' => 'MIKA','images' => 'MIKA.jpg','images_b' => 'MIKA.jpg'),
  array('name' => 'MADERA OPOCZNO','images' => 'MADERA_OPOCZNO.jpg,MADERA_OPOCZNO_1.jpg','images_b' => 'MADERA_OPOCZNO.jpg,MADERA_OPOCZNO_1.jpg'),
  array('name' => 'GWINEA','images' => 'GWINEA.jpg','images_b' => 'GWINEA.jpg'),
  array('name' => 'JESIEN','images' => 'JESIEN.jpg,JESIEN_1.jpg','images_b' => 'JESIEN.jpg,JESIEN_1.jpg')
);
