<?php

/**
 * This file is generated by Fork CMS, it contains
 * the mapping between a pageID and the URL
 * 
 * Fork CMS
 * @generated	2014-12-06 21:22:53
 */

// init var
$keys = array();

$keys[1] = '';
$keys[404] = '404';
$keys[418] = 'activate';
$keys[430] = 'automatisation';
$keys[429] = 'automatisation/71-buh';
$keys[431] = 'automatisation/72-zar';
$keys[405] = 'blogh';
$keys[413] = 'faq';
$keys[419] = 'forgot-password';
$keys[409] = 'istoriia';
$keys[439] = 'it-soprovozhdieniie';
$keys[444] = 'it-soprovozhdieniie/obuchieniie';
$keys[442] = 'it-soprovozhdieniie/poddierzhka';
$keys[441] = 'it-soprovozhdieniie/poddierzhka/poddierzhka-fizichieskikh-lits';
$keys[443] = 'it-soprovozhdieniie/poddierzhka/poddierzhka-iuridichieskikh-lits';
$keys[440] = 'it-soprovozhdieniie/vniedrieniie';
$keys[2] = 'karta-saita';
$keys[414] = 'kontakt';
$keys[422] = 'login';
$keys[424] = 'logout';
$keys[410] = 'lorem-ipsum';
$keys[406] = 'o-nas';
$keys[407] = 'o-nas/miestopolozhieniie';
$keys[408] = 'o-nas/o-nas';
$keys[411] = 'poisk';
$keys[425] = 'profile';
$keys[427] = 'profile/change-email';
$keys[428] = 'profile/change-password';
$keys[426] = 'profile/profile-settings';
$keys[415] = 'razoslannyie-rassylki';
$keys[417] = 'razoslannyie-rassylki/otpisat-sia';
$keys[416] = 'razoslannyie-rassylki/podpiska';
$keys[423] = 'register';
$keys[421] = 'resend-activation-e-mail';
$keys[420] = 'reset-password';
$keys[3] = 'soghlashieniie';
$keys[412] = 'tags';
$keys[433] = 'web';
$keys[432] = 'web/81-seo';
$keys[434] = 'web/sozdaniie-saitov';
$keys[437] = 'web/sozdaniie-saitov/intierniet-maghazin';
$keys[435] = 'web/sozdaniie-saitov/korporativnyi-sait';
$keys[436] = 'web/sozdaniie-saitov/sait-vizitka';
$keys[438] = 'web/vieb-dizain';

?>