<?php
/*********************/
/*                   */
/*  Version : 5.1.0  */
/*  Author  : RM     */
/*  Comment : 071223 */
/*                   */
/*********************/

header( "Content-Type: text/html; charset=windows-1251" );
$month = array( 1 => "января", 2 => "февраля", 3 => "марта", 4 => "апреля", 5 => "мая", 6 => "июня", 7 => "июля", 8 => "августа", 9 => "сентября", 10 => "октября", 11 => "ноября", 12 => "декабря" );
echo "<html>\n\t<head>\n\t\t<title>Штраф</title>\n\t\t<meta http-equiv=\"content-type\" content=\"text/html; charset=windows-1251\" />\n\t\t<link type=\"text/css\" rel=\"stylesheet\" href=\"/css/fee.css\" />\n\t</head>\n\t<body>\n\t\t<table class=\"fee\" cellspacing=\"0\">\n\t\t\t<tr>\n\t\t\t\t<td style=\"width: 50mm; height: 65mm; border-bottom: black 1.5px solid;\" align=\"center\" valign=\"middle\">\n\t\t\t\t\t<table style=\"width: 50mm; height: 100%;\" cellspacing=\"0\">\n\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t<td class=\"left\" style=\"vertical-align: top; letter-spacing: 0.2em;\">Извещение</td>\n\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t<td class=\"left\" style=\"vertical-align: bottom;\">Кассир</td>\n\t\t\t\t\t\t</tr>\n\t\t\t\t\t</table>\n\t\t\t\t</td>\n\t\t\t\t<td style=\"width: 130mm; height: 65mm; padding: 0mm 4mm 0mm 3mm; border-left: black 1.5px solid; border-bottom: black 1.5px solid;\">\n\t\t\t\t\t<table cellspacing=\"0\" align=\"center\" style=\"width: 123mm; height: 100%\">\n\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t<td>\n\t\t\t\t\t\t\t\t<table style=\"width: 100%;\" cellspacing=\"0\">\n\t\t\t\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t\t\t\t<td class=\"small\" style=\"text-align: right; vertical-align: middle;\" colspan=\"2\"><i>Форма &#8470; ПД-4сб (налог)</i></td>\n\t\t\t\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t\t\t\t<td class=\"text\" style=\"text-align: right; width: 43%;\">Статус&#160;плательщика&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"blank\" style=\"width: 7%;\">&#160;</td>\n\t\t\t\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t\t\t</table>\n\t\t\t\t\t\t\t</td>\n\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t<td>\n\t\t\t\t\t\t\t\t<table cellspacing=\"0\" width=\"100%\">\n\t\t\t\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t\t\t\t<td class=\"string\" style=\"width: 71%;\">УФК по Ярославской области (УФМС России по Яр. Обл.)&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td width=\"1%\" class=\"text\">&#160;&#160;КПП&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td width=\"20%\" class=\"blank\">760401001</td>\n\t\t\t\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t\t\t\t<td class=\"subscript\">(наименование получателя платежа)</td>\n\t\t\t\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t\t\t</table>\n\t\t\t\t\t\t\t</td>\n\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t<td>\n\t\t\t\t\t\t\t\t<table cellspacing=\"0\" width=\"100%\">\n\t\t\t\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t\t\t\t<td width=\"30%\" class=\"blank\">7604083179&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td width=\"2%\" class=\"text\">&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td width=\"35%\" class=\"string\">&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td width=\"2%\" class=\"text\">&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td width=\"31%\" class=\"blank\">";
echo $_POST['okato'];
echo "</td>\n\t\t\t\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t\t\t\t<td class=\"subscript\">ИНН налогового органа*</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"subscript\">&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"subscript\">и его сокращенное наименование</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"subscript\">&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"subscript\">(Код ОКТМО)</td>\n\t\t\t\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t\t\t</table>\n\t\t\t\t\t\t\t</td>\n\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t<td>\n\t\t\t\t\t\t\t\t<table cellspacing=\"0\" width=\"100%\">\n\t\t\t\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t\t\t\t<td width=\"50%\" class=\"blank\">40101810700000010010</td>\n\t\t\t\t\t\t\t\t\t\t<td width=\"3%\" class=\"text\" align=\"center\">в</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"string\">ГРКЦ ГУ БР по Яр. обл. г. Ярославль</td>\n\t\t\t\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t\t\t\t<td class=\"subscript\">(номер счета получателя платежа)</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"subscript\">&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"subscript\">(наименование банка)</td>\n\t\t\t\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t\t\t</table>\n\t\t\t\t\t\t\t</td>\n\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t<td>\n\t\t\t\t\t\t\t\t<table cellspacing=\"0\" width=\"100%\">\n\t\t\t\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t\t\t\t<td class=\"text\">БИК:&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td width=\"27%\" class=\"blank\">047888001</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"text nowr\" align=\"right\">&#160;Кор./сч.:&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td width=\"60%\" class=\"blank\">&#160;</td>\n\t\t\t\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t\t\t</table>\n\t\t\t\t\t\t\t</td>\n\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t<td>\n\t\t\t\t\t\t\t\t<table cellspacing=\"0\" width=\"100%\">\n\t\t\t\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t\t\t\t<td class=\"string\" width=\"54%\"><span id=\"type\">";
echo $_POST['type'];
echo "</span><br />";
echo $_POST['fine'];
echo "</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"text\" width=\"2%\">&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td width=\"42%\" class=\"blank\">";
echo $_POST['kbk'];
echo "</td>\n\t\t\t\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t\t\t\t<td class=\"subscript\">(наименование платежа)</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"subscript\">&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"subscript\">(код бюджетной классификации КБК)</td>\n\t\t\t\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t\t\t</table>\n\t\t\t\t\t\t\t</td>\n\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t<td>\n\t\t\t\t\t\t\t\t<table cellspacing=\"0\" width=\"100%\">\n\t\t\t\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t\t\t\t<td class=\"text\" width=\"1%\">Плательщик&#160;(Ф.И.О)&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"string\">";
echo $_POST['name'];
echo "</td>\n\t\t\t\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t\t\t</table>\n\t\t\t\t\t\t\t</td>\n\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t<td>\n\t\t\t\t\t\t\t\t<table cellspacing=\"0\" width=\"100%\">\n\t\t\t\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t\t\t\t<td class=\"text\" width=\"1%\">Адрес&#160;плательщика:&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"string\">";
echo $_POST['address'];
echo "&#160;</td>\n\t\t\t\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t\t\t</table>\n\t\t\t\t\t\t\t</td>\n\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t<td>\n\t\t\t\t\t\t\t\t<table cellspacing=\"0\" width=\"100%\">\n\t\t\t\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t\t\t\t<td class=\"small\">ИНН&#160;плательщика:&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td width=\"36%\" class=\"blank\">&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"small nowr\">&#160;&#8470;&#160;л/с&#160;плательщика&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td width=\"36%\" class=\"blank\">&#160;</td>\n\t\t\t\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t\t\t</table>\n\t\t\t\t\t\t\t</td>\n\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t<td>\n\t\t\t\t\t\t\t\t<table cellspacing=\"0\" width=\"100%\">\n\t\t\t\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t\t\t\t<td class=\"text\" width=\"1%\">Сумма:&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"blank\" width=\"20%\">";
echo $_POST['amount'];
echo "</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"text\" width=\"1%\">&#160;руб.&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"blank\" width=\"8%\">00</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"text\" width=\"1%\">&#160;коп.</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"text\" width=\"10%\">&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"text\" width=\"1%\">Статус:&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"blank\" width=\"10%\">&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"text\" width=\"20%\">&#160;</td>\n\t\t\t\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t\t\t</table>\n\t\t\t\t\t\t\t</td>\n\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t<td>\n\t\t\t\t\t\t\t\t<table cellspacing=\"0\" width=\"100%\">\n\t\t\t\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t\t\t\t<td class=\"text\" width=\"24%\" style=\"padding-top: 1mm;\"><b>Плательщик&#160;(подпись):&#160;</b></td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"string\" width=\"30%\">&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"text\" width=\"4%\">&#160;&#160;&#160;Дата:&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"blank\" width=\"8%\">";
echo date( "d" );
echo "</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"text\" width=\"2%\">&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"string\" width=\"20%\">&#160;";
echo $month[date( "n" )];
echo "&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"text\" width=\"3%\">&#160;20</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"blank\" width=\"5%\">";
echo date( "y" );
echo "</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"text\" width=\"3%\">&#160;г.</td>\n\t\t\t\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t\t\t</table>\n\t\t\t\t\t\t\t</td>\n\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t<td class=\"subscript\" style=\"text-align: left;\"><i>* или иной государственный орган исполнительной власти</i></td>\n\t\t\t\t\t\t</tr>\n\t\t\t\t\t</table>\n\t\t\t\t</td>\n\t\t\t</tr>\n\t\t\t<tr>\n\t\t\t\t<td style=\"width: 50mm; height: 80mm; vertical-align: bottom;\" class=\"left\">Квитанция<br>\n\t\t\t\t\t<br>\n\t\t\t\t\tКассир</td>\n\t\t\t\t<td style=\"width: 130mm; height: 80mm; padding: 0mm 4mm 0mm 3mm; border-left: black 1.5px solid;\">\n\n\t\t\t\t\t<table cellspacing=\"0\" align=\"center\" style=\"width: 123mm; height: 100%\">\n\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t<td>\n\t\t\t\t\t\t\t\t<table cellspacing=\"0\" width=\"100%\">\n\t\t\t\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t\t\t\t<td class=\"string\" style=\"width: 71%; height: 10mm;\">УФК по Ярославской области (УФМС России по Яр. Обл.)&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td width=\"1%\" class=\"text\">&#160;&#160;КПП&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td width=\"20%\" class=\"blank\">760401001</td>\n\t\t\t\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t\t\t\t<td class=\"subscript\">(наименование получателя платежа)</td>\n\t\t\t\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t\t\t</table>\n\t\t\t\t\t\t\t</td>\n\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t<td>\n\t\t\t\t\t\t\t\t<table cellspacing=\"0\" width=\"100%\">\n\t\t\t\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t\t\t\t<td width=\"30%\" class=\"blank\">7604083179&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td width=\"2%\" class=\"text\">&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td width=\"35%\" class=\"string\">&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td width=\"2%\" class=\"text\">&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td width=\"31%\" class=\"blank\">";
echo $_POST['okato'];
echo "</td>\n\t\t\t\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t\t\t\t<td class=\"subscript\">ИНН налогового органа*</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"subscript\">&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"subscript\">и его сокращенное наименование</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"subscript\">&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"subscript\">(Код ОКТМО)</td>\n\t\t\t\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t\t\t</table>\n\t\t\t\t\t\t\t</td>\n\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t<td>\n\t\t\t\t\t\t\t\t<table cellspacing=\"0\" width=\"100%\">\n\t\t\t\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t\t\t\t<td width=\"50%\" class=\"blank\">40101810700000010010</td>\n\t\t\t\t\t\t\t\t\t\t<td width=\"3%\" class=\"text\" align=\"center\">в</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"string\">ГРКЦ ГУ БР по Яр. обл. г. Ярославль</td>\n\t\t\t\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t\t\t\t<td class=\"subscript\">(номер счета получателя платежа)</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"subscript\">&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"subscript\">(наименование банка)</td>\n\t\t\t\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t\t\t</table>\n\t\t\t\t\t\t\t</td>\n\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t<td>\n\t\t\t\t\t\t\t\t<table cellspacing=\"0\" width=\"100%\">\n\t\t\t\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t\t\t\t<td class=\"text\">БИК:&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td width=\"27%\" class=\"blank\">047888001</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"text nowr\" align=\"right\">&#160;Кор./сч.:&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td width=\"60%\" class=\"blank\">&#160;</td>\n\t\t\t\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t\t\t</table>\n\t\t\t\t\t\t\t</td>\n\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t<td>\n\t\t\t\t\t\t\t\t<table cellspacing=\"0\" width=\"100%\">\n\t\t\t\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t\t\t\t<td class=\"string\" width=\"54%\">";
echo $_POST['type'];
echo "<br />";
echo $_POST['fine'];
echo "</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"text\" width=\"2%\">&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td width=\"42%\" class=\"blank\">";
echo $_POST['kbk'];
echo "</td>\n\t\t\t\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t\t\t\t<td class=\"subscript\">(наименование платежа)</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"subscript\">&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"subscript\">(код бюджетной классификации КБК)</td>\n\t\t\t\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t\t\t</table>\n\t\t\t\t\t\t\t</td>\n\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t<td>\n\t\t\t\t\t\t\t\t<table cellspacing=\"0\" width=\"100%\">\n\t\t\t\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t\t\t\t<td class=\"text\" width=\"1%\">Плательщик&#160;(Ф.И.О)&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"string\">";
echo $_POST['name'];
echo "</td>\n\t\t\t\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t\t\t</table>\n\t\t\t\t\t\t\t</td>\n\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t<td>\n\t\t\t\t\t\t\t\t<table cellspacing=\"0\" width=\"100%\">\n\t\t\t\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t\t\t\t<td class=\"text\" width=\"1%\">Адрес&#160;плательщика:&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"string\">";
echo $_POST['address'];
echo "&#160;</td>\n\t\t\t\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t\t\t</table>\n\t\t\t\t\t\t\t</td>\n\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t<td>\n\t\t\t\t\t\t\t\t<table cellspacing=\"0\" width=\"100%\">\n\t\t\t\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t\t\t\t<td class=\"small\">ИНН&#160;плательщика:&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td width=\"36%\" class=\"blank\">&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"small nowr\">&#160;&#8470;&#160;л/с&#160;плательщика&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td width=\"36%\" class=\"blank\">&#160;</td>\n\t\t\t\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t\t\t</table>\n\t\t\t\t\t\t\t</td>\n\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t<td>\n\t\t\t\t\t\t\t\t<table cellspacing=\"0\" width=\"100%\">\n\t\t\t\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t\t\t\t<td class=\"text\" width=\"1%\">Сумма:&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"blank\" width=\"20%\">";
echo $_POST['amount'];
echo "</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"text\" width=\"1%\">&#160;руб.&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"blank\" width=\"8%\">00</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"text\" width=\"1%\">&#160;коп.</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"text\" width=\"10%\">&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"text\" width=\"1%\">Статус:&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"blank\" width=\"10%\">&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"text\" width=\"20%\">&#160;</td>\n\t\t\t\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t\t\t</table>\n\t\t\t\t\t\t\t</td>\n\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t<td>\n\t\t\t\t\t\t\t\t<table cellspacing=\"0\" width=\"100%\">\n\t\t\t\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t\t\t\t<td class=\"text\" width=\"24%\" style=\"padding-top: 1mm;\"><b>Плательщик&#160;(подпись):&#160;</b></td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"string\" width=\"30%\">&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"text\" width=\"4%\">&#160;&#160;&#160;Дата:&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"blank\" width=\"8%\">";
echo date( "d" );
echo "</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"text\" width=\"2%\">&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"string\" width=\"20%\">&#160;";
echo $month[date( "n" )];
echo "&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"text\" width=\"3%\">&#160;20</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"blank\" width=\"5%\">";
echo date( "y" );
echo "</td>\n\t\t\t\t\t\t\t\t\t\t<td class=\"text\" width=\"3%\">&#160;г.</td>\n\t\t\t\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t\t\t</table>\n\t\t\t\t\t\t\t</td>\n\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t<td class=\"subscript\" style=\"text-align: left;\"><i>* или иной государственный орган исполнительной власти</i></td>\n\t\t\t\t\t\t</tr>\n\t\t\t\t\t</table>\n\t\t\t\t</td>\n\t\t\t</tr>\n\t\t</table>\n\t</body>\n</html>";
?>
