<?php
/*
 *
 * This file is generated by the Backend, it contains
 * more information about the navigation in the backend. Do NOT edit.
 * 
 * @author Backend
 * @generated	2014-09-17 13:27:46
 */

$navigation = array(
	array(
		'url' => 'dashboard/index',
		'label' => 'Dashboard'
	),
	array(
		'url' => 'pages/index',
		'label' => 'Pages',
		'selected_for' => array(
			'pages/add',
			'pages/edit'
		)
	),
	array(
		'url' => 'search/statistics',
		'label' => 'Modules',
		'children' => array(
			array(
				'url' => 'search/statistics',
				'label' => 'Search',
				'children' => array(
					array(
						'url' => 'search/statistics',
						'label' => 'Statistics'
					),
					array(
						'url' => 'search/synonyms',
						'label' => 'Synonyms',
						'selected_for' => array(
							'search/add_synonym',
							'search/edit_synonym'
						)
					)
				)
			),
			array(
				'url' => 'content_blocks/index',
				'label' => 'ContentBlocks',
				'selected_for' => array(
					'content_blocks/add',
					'content_blocks/edit'
				)
			),
			array(
				'url' => 'tags/index',
				'label' => 'Tags',
				'selected_for' => array(
					'tags/edit'
				)
			),
			array(
				'url' => 'blog/index',
				'label' => 'Blog',
				'children' => array(
					array(
						'url' => 'blog/index',
						'label' => 'Articles',
						'selected_for' => array(
							'blog/add',
							'blog/edit',
							'blog/import_wordpress'
						)
					),
					array(
						'url' => 'blog/comments',
						'label' => 'Comments',
						'selected_for' => array(
							'blog/edit_comment'
						)
					),
					array(
						'url' => 'blog/categories',
						'label' => 'Categories',
						'selected_for' => array(
							'blog/add_category',
							'blog/edit_category'
						)
					)
				)
			),
			array(
				'url' => 'faq/index',
				'label' => 'Faq',
				'children' => array(
					array(
						'url' => 'faq/index',
						'label' => 'Questions',
						'selected_for' => array(
							'faq/add',
							'faq/edit'
						)
					),
					array(
						'url' => 'faq/categories',
						'label' => 'Categories',
						'selected_for' => array(
							'faq/add_category',
							'faq/edit_category'
						)
					)
				)
			),
			array(
				'url' => 'form_builder/index',
				'label' => 'FormBuilder',
				'selected_for' => array(
					'form_builder/add',
					'form_builder/edit',
					'form_builder/data',
					'form_builder/data_details'
				)
			),
			array(
				'url' => 'location/index',
				'label' => 'Location',
				'selected_for' => array(
					'location/add',
					'location/edit'
				)
			),
			array(
				'url' => 'profiles/index',
				'label' => 'Profiles',
				'children' => array(
					array(
						'url' => 'profiles/index',
						'label' => 'Overview',
						'selected_for' => array(
							'profiles/add',
							'profiles/edit',
							'profiles/add_profile_group',
							'profiles/edit_profile_group',
							'profiles/import'
						)
					),
					array(
						'url' => 'profiles/groups',
						'label' => 'Groups',
						'selected_for' => array(
							'profiles/add_group',
							'profiles/edit_group'
						)
					)
				)
			),
			array(
				'url' => 'slideshow/index',
				'label' => 'Slideshow',
				'children' => array(
					array(
						'url' => 'slideshow/index',
						'label' => 'Galleries',
						'selected_for' => array(
							'slideshow/add',
							'slideshow/edit',
							'slideshow/edit_image',
							'slideshow/add_image'
						)
					),
					array(
						'url' => 'slideshow/categories',
						'label' => 'Categories',
						'selected_for' => array(
							'slideshow/add_category',
							'slideshow/edit_category'
						)
					)
				)
			)
		)
	),
	array(
		'url' => 'analytics/index',
		'label' => 'Marketing',
		'children' => array(
			array(
				'url' => 'analytics/index',
				'label' => 'Analytics',
				'selected_for' => array(
					'analytics/loading'
				),
				'children' => array(
					array(
						'url' => 'analytics/content',
						'label' => 'Content'
					),
					array(
						'url' => 'analytics/all_pages',
						'label' => 'AllPages'
					),
					array(
						'url' => 'analytics/exit_pages',
						'label' => 'ExitPages'
					),
					array(
						'url' => 'analytics/landing_pages',
						'label' => 'LandingPages',
						'selected_for' => array(
							'analytics/add_landing_page',
							'analytics/edit_landing_page',
							'analytics/detail_page'
						)
					)
				)
			)
		)
	),
	array(
		'url' => 'mailmotor/index',
		'label' => 'Mailmotor',
		'children' => array(
			array(
				'url' => 'mailmotor/index',
				'label' => 'Newsletters',
				'selected_for' => array(
					'mailmotor/add',
					'mailmotor/edit',
					'mailmotor/edit_mailing_campaign',
					'mailmotor/statistics',
					'mailmotor/statistics_link',
					'mailmotor/statistics_bounces',
					'mailmotor/statistics_campaign',
					'mailmotor/statistics_opens'
				)
			),
			array(
				'url' => 'mailmotor/campaigns',
				'label' => 'Campaigns',
				'selected_for' => array(
					'mailmotor/add_campaign',
					'mailmotor/edit_campaign',
					'mailmotor/statistics_campaigns'
				)
			),
			array(
				'url' => 'mailmotor/groups',
				'label' => 'MailmotorGroups',
				'selected_for' => array(
					'mailmotor/add_group',
					'mailmotor/edit_group',
					'mailmotor/custom_fields',
					'mailmotor/add_custom_field',
					'mailmotor/import_groups'
				)
			),
			array(
				'url' => 'mailmotor/addresses',
				'label' => 'Addresses',
				'selected_for' => array(
					'mailmotor/add_address',
					'mailmotor/edit_address',
					'mailmotor/import_addresses'
				)
			)
		)
	),
	array(
		'url' => 'settings/index',
		'label' => 'Settings',
		'children' => array(
			array(
				'url' => 'settings/index',
				'label' => 'General'
			),
			array(
				'url' => 'settings/email',
				'label' => 'Advanced',
				'children' => array(
					array(
						'url' => 'settings/email',
						'label' => 'Email'
					),
					array(
						'url' => 'settings/seo',
						'label' => 'SEO'
					)
				)
			),
			array(
				'url' => 'locale/index',
				'label' => 'Translations',
				'selected_for' => array(
					'locale/add',
					'locale/edit',
					'locale/import',
					'locale/analyse'
				)
			),
			array(
				'url' => 'users/index',
				'label' => 'Users',
				'selected_for' => array(
					'users/add',
					'users/edit'
				)
			),
			array(
				'url' => 'groups/index',
				'label' => 'Groups',
				'selected_for' => array(
					'groups/add',
					'groups/edit'
				)
			),
			array(
				'url' => 'extensions/modules',
				'label' => 'Modules',
				'children' => array(
					array(
						'url' => 'extensions/modules',
						'label' => 'Overview',
						'selected_for' => array(
							'extensions/detail_module',
							'extensions/upload_module'
						)
					),
					array(
						'url' => 'pages/settings',
						'label' => 'Pages'
					),
					array(
						'url' => 'search/settings',
						'label' => 'Search'
					),
					array(
						'url' => 'analytics/settings',
						'label' => 'Analytics'
					),
					array(
						'url' => 'blog/settings',
						'label' => 'Blog'
					),
					array(
						'url' => 'faq/settings',
						'label' => 'Faq'
					),
					array(
						'url' => 'location/settings',
						'label' => 'Location'
					),
					array(
						'url' => 'mailmotor/settings',
						'label' => 'Mailmotor'
					),
					array(
						'url' => 'slideshow/settings',
						'label' => 'Slideshow'
					)
				)
			),
			array(
				'url' => 'extensions/themes',
				'label' => 'Themes',
				'children' => array(
					array(
						'url' => 'extensions/themes',
						'label' => 'ThemesSelection',
						'selected_for' => array(
							'extensions/upload_theme',
							'extensions/detail_theme'
						)
					),
					array(
						'url' => 'extensions/theme_templates',
						'label' => 'Templates',
						'selected_for' => array(
							'extensions/add_theme_template',
							'extensions/edit_theme_template'
						)
					)
				)
			)
		)
	)
);

?>