parameters:
    database.driver:        mysql
    database.host:          localhost
    database.port:          3306
    database.name:          anastosi_base
    database.user:          anastosi_root
    database.password:      anastosipass

    kernel.charset:         'utf-8'
    kernel.secret:          gZl0SLOrkdtWiXnCyBOO60lg4rYviiKk

    fork.debug_email:       deniuscoder@mail.ru
    fork.debug_message:     'Internal error.'
    fork.version:           '3.8.1'

    site.protocol:          http
    site.domain:            anastosi.ru
    site.default_title:     Fork CMS
    site.multilanguage:     false
    site.default_language:  ru
    site.path_www:          %kernel.root_dir%/..
    site.path_library:      %site.path_www%/library

    action.group_tag:       \@actiongroup
    action.rights_level:    7
