<?
$MESS["SLIDER_WIDTH_TIP"] = GetMessage("ITLOGIC_BXSLIDER_UKAZATQ_TOLQKO_CISLO");
$MESS["SLIDER_CAPTIONS_TIP"] = GetMessage("ITLOGIC_BXSLIDER_PODPISQ_BERETSA_IZ_N");
$MESS["SLIDER_AUTO_TIP"] = GetMessage("ITLOGIC_BXSLIDER_PRI_VKLUCENNOY_OPCII");
$MESS["SLIDER_HIDECONTROLONEND_TIP"] = GetMessage("ITLOGIC_BXSLIDER_PRI_VKLUCENII_BUDET");
$MESS["SLIDER_RESPONSIVE_TIP"] = GetMessage("ITLOGIC_BXSLIDER_AVTOMATICESKOE_PODST");
?>