<?php

/**
 * This file is generated by Fork CMS, it contains
 * the mapping between a pageID and the URL
 * 
 * Fork CMS
 * @generated	2014-10-16 14:38:44
 */

// init var
$keys = array();

$keys[1] = '';
$keys[404] = '404';
$keys[429] = 'about';
$keys[418] = 'activate';
$keys[419] = 'forgot-password';
$keys[422] = 'login';
$keys[424] = 'logout';
$keys[411] = 'poisk';
$keys[425] = 'profile';
$keys[427] = 'profile/change-email';
$keys[428] = 'profile/change-password';
$keys[426] = 'profile/profile-settings';
$keys[415] = 'razoslannyie-rassylki';
$keys[417] = 'razoslannyie-rassylki/otpisat-sia';
$keys[416] = 'razoslannyie-rassylki/podpiska';
$keys[423] = 'register';
$keys[421] = 'resend-activation-e-mail';
$keys[420] = 'reset-password';
$keys[412] = 'tags';

?>