<?php

/**
 * This file is generated by Fork CMS, it contains
 * more information about the page-structure
 * 
 * Fork CMS
 * @generated	2014-10-16 14:38:44
 */

// init var
$navigation = array();

$navigation['root'][0][404]['page_id'] = 404;
$navigation['root'][0][404]['url'] = '404';
$navigation['root'][0][404]['full_url'] = '/404';
$navigation['root'][0][404]['title'] = '404';
$navigation['root'][0][404]['navigation_title'] = '404';
$navigation['root'][0][404]['has_extra'] = false;
$navigation['root'][0][404]['no_follow'] = false;
$navigation['root'][0][404]['hidden'] = false;
$navigation['root'][0][404]['extra_blocks'] = null;
$navigation['root'][0][404]['tree_type'] = 'error';

$navigation['root'][0][411]['page_id'] = 411;
$navigation['root'][0][411]['url'] = 'poisk';
$navigation['root'][0][411]['full_url'] = '/poisk';
$navigation['root'][0][411]['title'] = 'Поиск';
$navigation['root'][0][411]['navigation_title'] = 'Поиск';
$navigation['root'][0][411]['has_extra'] = true;
$navigation['root'][0][411]['no_follow'] = false;
$navigation['root'][0][411]['hidden'] = false;
$navigation['root'][0][411]['extra_blocks'] = array(array('id' => 2, 'module' => 'Search', 'action' => null));
$navigation['root'][0][411]['tree_type'] = 'page';

$navigation['root'][0][412]['page_id'] = 412;
$navigation['root'][0][412]['url'] = 'tags';
$navigation['root'][0][412]['full_url'] = '/tags';
$navigation['root'][0][412]['title'] = 'Tags';
$navigation['root'][0][412]['navigation_title'] = 'Tags';
$navigation['root'][0][412]['has_extra'] = true;
$navigation['root'][0][412]['no_follow'] = false;
$navigation['root'][0][412]['hidden'] = false;
$navigation['root'][0][412]['extra_blocks'] = array(array('id' => 12, 'module' => 'Tags', 'action' => null));
$navigation['root'][0][412]['tree_type'] = 'page';

$navigation['root'][0][415]['page_id'] = 415;
$navigation['root'][0][415]['url'] = 'razoslannyie-rassylki';
$navigation['root'][0][415]['full_url'] = '/razoslannyie-rassylki';
$navigation['root'][0][415]['title'] = 'Разосланные рассылки';
$navigation['root'][0][415]['navigation_title'] = 'Разосланные рассылки';
$navigation['root'][0][415]['has_extra'] = true;
$navigation['root'][0][415]['no_follow'] = false;
$navigation['root'][0][415]['hidden'] = false;
$navigation['root'][0][415]['extra_blocks'] = array(array('id' => 21, 'module' => 'Mailmotor', 'action' => null));
$navigation['root'][0][415]['tree_type'] = 'page';

$navigation['root'][0][418]['page_id'] = 418;
$navigation['root'][0][418]['url'] = 'activate';
$navigation['root'][0][418]['full_url'] = '/activate';
$navigation['root'][0][418]['title'] = 'Activate';
$navigation['root'][0][418]['navigation_title'] = 'Activate';
$navigation['root'][0][418]['has_extra'] = true;
$navigation['root'][0][418]['no_follow'] = false;
$navigation['root'][0][418]['hidden'] = false;
$navigation['root'][0][418]['extra_blocks'] = array(array('id' => 25, 'module' => 'Profiles', 'action' => 'Activate'));
$navigation['root'][0][418]['tree_type'] = 'page';

$navigation['root'][0][419]['page_id'] = 419;
$navigation['root'][0][419]['url'] = 'forgot-password';
$navigation['root'][0][419]['full_url'] = '/forgot-password';
$navigation['root'][0][419]['title'] = 'Forgot password';
$navigation['root'][0][419]['navigation_title'] = 'Forgot password';
$navigation['root'][0][419]['has_extra'] = true;
$navigation['root'][0][419]['no_follow'] = false;
$navigation['root'][0][419]['hidden'] = false;
$navigation['root'][0][419]['extra_blocks'] = array(array('id' => 26, 'module' => 'Profiles', 'action' => 'ForgotPassword'));
$navigation['root'][0][419]['tree_type'] = 'page';

$navigation['root'][0][420]['page_id'] = 420;
$navigation['root'][0][420]['url'] = 'reset-password';
$navigation['root'][0][420]['full_url'] = '/reset-password';
$navigation['root'][0][420]['title'] = 'Reset password';
$navigation['root'][0][420]['navigation_title'] = 'Reset password';
$navigation['root'][0][420]['has_extra'] = true;
$navigation['root'][0][420]['no_follow'] = false;
$navigation['root'][0][420]['hidden'] = false;
$navigation['root'][0][420]['extra_blocks'] = array(array('id' => 34, 'module' => 'Profiles', 'action' => 'ResetPassword'));
$navigation['root'][0][420]['tree_type'] = 'page';

$navigation['root'][0][421]['page_id'] = 421;
$navigation['root'][0][421]['url'] = 'resend-activation-e-mail';
$navigation['root'][0][421]['full_url'] = '/resend-activation-e-mail';
$navigation['root'][0][421]['title'] = 'Resend activation e-mail';
$navigation['root'][0][421]['navigation_title'] = 'Resend activation e-mail';
$navigation['root'][0][421]['has_extra'] = true;
$navigation['root'][0][421]['no_follow'] = false;
$navigation['root'][0][421]['hidden'] = false;
$navigation['root'][0][421]['extra_blocks'] = array(array('id' => 35, 'module' => 'Profiles', 'action' => 'ResendActivation'));
$navigation['root'][0][421]['tree_type'] = 'page';

$navigation['root'][0][422]['page_id'] = 422;
$navigation['root'][0][422]['url'] = 'login';
$navigation['root'][0][422]['full_url'] = '/login';
$navigation['root'][0][422]['title'] = 'Login';
$navigation['root'][0][422]['navigation_title'] = 'Login';
$navigation['root'][0][422]['has_extra'] = true;
$navigation['root'][0][422]['no_follow'] = false;
$navigation['root'][0][422]['hidden'] = false;
$navigation['root'][0][422]['extra_blocks'] = array(array('id' => 28, 'module' => 'Profiles', 'action' => 'Login'));
$navigation['root'][0][422]['tree_type'] = 'page';

$navigation['root'][0][423]['page_id'] = 423;
$navigation['root'][0][423]['url'] = 'register';
$navigation['root'][0][423]['full_url'] = '/register';
$navigation['root'][0][423]['title'] = 'Register';
$navigation['root'][0][423]['navigation_title'] = 'Register';
$navigation['root'][0][423]['has_extra'] = true;
$navigation['root'][0][423]['no_follow'] = false;
$navigation['root'][0][423]['hidden'] = false;
$navigation['root'][0][423]['extra_blocks'] = array(array('id' => 33, 'module' => 'Profiles', 'action' => 'Register'));
$navigation['root'][0][423]['tree_type'] = 'page';

$navigation['root'][0][424]['page_id'] = 424;
$navigation['root'][0][424]['url'] = 'logout';
$navigation['root'][0][424]['full_url'] = '/logout';
$navigation['root'][0][424]['title'] = 'Logout';
$navigation['root'][0][424]['navigation_title'] = 'Logout';
$navigation['root'][0][424]['has_extra'] = true;
$navigation['root'][0][424]['no_follow'] = false;
$navigation['root'][0][424]['hidden'] = false;
$navigation['root'][0][424]['extra_blocks'] = array(array('id' => 29, 'module' => 'Profiles', 'action' => 'Logout'));
$navigation['root'][0][424]['tree_type'] = 'page';

$navigation['root'][0][425]['page_id'] = 425;
$navigation['root'][0][425]['url'] = 'profile';
$navigation['root'][0][425]['full_url'] = '/profile';
$navigation['root'][0][425]['title'] = 'Profile';
$navigation['root'][0][425]['navigation_title'] = 'Profile';
$navigation['root'][0][425]['has_extra'] = true;
$navigation['root'][0][425]['no_follow'] = false;
$navigation['root'][0][425]['hidden'] = false;
$navigation['root'][0][425]['extra_blocks'] = array(array('id' => 27, 'module' => 'Profiles', 'action' => null));
$navigation['root'][0][425]['tree_type'] = 'page';

$navigation['footer'][0][429]['page_id'] = 429;
$navigation['footer'][0][429]['url'] = 'about';
$navigation['footer'][0][429]['full_url'] = '/about';
$navigation['footer'][0][429]['title'] = 'About';
$navigation['footer'][0][429]['navigation_title'] = 'About';
$navigation['footer'][0][429]['has_extra'] = false;
$navigation['footer'][0][429]['no_follow'] = false;
$navigation['footer'][0][429]['hidden'] = false;
$navigation['footer'][0][429]['extra_blocks'] = null;
$navigation['footer'][0][429]['tree_type'] = 'page';

$navigation['page'][0][1]['page_id'] = 1;
$navigation['page'][0][1]['url'] = '';
$navigation['page'][0][1]['full_url'] = '/';
$navigation['page'][0][1]['title'] = 'Главная';
$navigation['page'][0][1]['navigation_title'] = 'Главная';
$navigation['page'][0][1]['has_extra'] = false;
$navigation['page'][0][1]['no_follow'] = false;
$navigation['page'][0][1]['hidden'] = false;
$navigation['page'][0][1]['extra_blocks'] = null;
$navigation['page'][0][1]['tree_type'] = 'home';

$navigation['page'][415][416]['page_id'] = 416;
$navigation['page'][415][416]['url'] = 'podpiska';
$navigation['page'][415][416]['full_url'] = '/razoslannyie-rassylki/podpiska';
$navigation['page'][415][416]['title'] = 'Подписка';
$navigation['page'][415][416]['navigation_title'] = 'Подписка';
$navigation['page'][415][416]['has_extra'] = true;
$navigation['page'][415][416]['no_follow'] = false;
$navigation['page'][415][416]['hidden'] = false;
$navigation['page'][415][416]['extra_blocks'] = array(array('id' => 22, 'module' => 'Mailmotor', 'action' => 'Subscribe'));
$navigation['page'][415][416]['tree_type'] = 'page';

$navigation['page'][415][417]['page_id'] = 417;
$navigation['page'][415][417]['url'] = 'otpisat-sia';
$navigation['page'][415][417]['full_url'] = '/razoslannyie-rassylki/otpisat-sia';
$navigation['page'][415][417]['title'] = 'Отписаться';
$navigation['page'][415][417]['navigation_title'] = 'Отписаться';
$navigation['page'][415][417]['has_extra'] = true;
$navigation['page'][415][417]['no_follow'] = false;
$navigation['page'][415][417]['hidden'] = false;
$navigation['page'][415][417]['extra_blocks'] = array(array('id' => 23, 'module' => 'Mailmotor', 'action' => 'Unsubscribe'));
$navigation['page'][415][417]['tree_type'] = 'page';

$navigation['page'][425][426]['page_id'] = 426;
$navigation['page'][425][426]['url'] = 'profile-settings';
$navigation['page'][425][426]['full_url'] = '/profile/profile-settings';
$navigation['page'][425][426]['title'] = 'Profile settings';
$navigation['page'][425][426]['navigation_title'] = 'Profile settings';
$navigation['page'][425][426]['has_extra'] = true;
$navigation['page'][425][426]['no_follow'] = false;
$navigation['page'][425][426]['hidden'] = false;
$navigation['page'][425][426]['extra_blocks'] = array(array('id' => 32, 'module' => 'Profiles', 'action' => 'Settings'));
$navigation['page'][425][426]['tree_type'] = 'page';

$navigation['page'][425][427]['page_id'] = 427;
$navigation['page'][425][427]['url'] = 'change-email';
$navigation['page'][425][427]['full_url'] = '/profile/change-email';
$navigation['page'][425][427]['title'] = 'Change email';
$navigation['page'][425][427]['navigation_title'] = 'Change email';
$navigation['page'][425][427]['has_extra'] = true;
$navigation['page'][425][427]['no_follow'] = false;
$navigation['page'][425][427]['hidden'] = false;
$navigation['page'][425][427]['extra_blocks'] = array(array('id' => 30, 'module' => 'Profiles', 'action' => 'ChangeEmail'));
$navigation['page'][425][427]['tree_type'] = 'page';

$navigation['page'][425][428]['page_id'] = 428;
$navigation['page'][425][428]['url'] = 'change-password';
$navigation['page'][425][428]['full_url'] = '/profile/change-password';
$navigation['page'][425][428]['title'] = 'Change password';
$navigation['page'][425][428]['navigation_title'] = 'Change password';
$navigation['page'][425][428]['has_extra'] = true;
$navigation['page'][425][428]['no_follow'] = false;
$navigation['page'][425][428]['hidden'] = false;
$navigation['page'][425][428]['extra_blocks'] = array(array('id' => 31, 'module' => 'Profiles', 'action' => 'ChangePassword'));
$navigation['page'][425][428]['tree_type'] = 'page';

?>