app: artisan_dealers
title: Artisan.Dealers
charset: utf-8
mode: development # If set this mode will be used
default_mode: development
load_named_conf: 0
db_prefix: ad_

mvc:
  dirs:
    models: models
    controllers: controllers
    views: views
  use_subdirs:
    controllers: 0
    models: 0
    views: 1

views:
  forms:
    label: '<label for="{id}">{title}</label>'
use_smarty: 1
smarty:
  compile_dir: .zf_compiled/
  cache_dir: .zf_cache/

kcaptcha:
  bgcolor: '255-255-255'

page:
  extract_variables: 1
  extract_forms: 1

default_controller: content
has_common_controller: 1
vars_keys: [id, pid, page, pos, application, god_mode, sort, dir, ajax, type, offer, did, table, for_print, action, novice, sale]

session:
  save_path: .zf_tmp
  autostart: 1
  lifetime: 0
  update_lifetime: 0
  name: artisan_session

# Settings depending on where application is running.
run_at: 
  semen:
    cond: {ip: [192.168.0.231], host: [local.artisan-project.ru]}
    mode: development
    db_engine: mysqlidb
    db_charset: utf-8
    db_use_pconnection: 0
    db_host: localhost
    db_name: artisan-project
    db_user: root
    db_pass: 123321
    db_sql_mode: ''
    yandex:
      map: 'AKOG8E4BAAAALizHQwMAoN_aHuKG0-ZeeSolkZvKPCg2mdEAAAAAAAAAAABR6r4aeg6Y87XSpTpWgjr5vfissg==~AEnB8U4BAAAAfXjVAQIAdj4YN6uGLKDoLKF_kFGMOQxVDdMAAAAAAAAAAABWZkVWtEgDB8HNUOVnT0Ydi96-Lw=='
  #demo:
  #  cond: {host: [new.artisan-project.ru]}
  #  mode: production
  #  db_engine: mysql
  #  db_charset: utf-8
  #  db_use_pconnection: 0
  #  db_host: u261784.mysql.masterhost.ru
  #  db_name: u261784_window
  #  db_user: u261784
  #  db_pass: 3averoffi7
  #  yandex:
  #    map: 'AFUSXEwBAAAAX858DAIAJ6tFb4Y26gulCl50mUPX9yaBATwAAAAAAAAAAABcWOQn4_4CCC5pMceteYL6Tp8Uhw=='
  forgon:
    cond: {host: [artisan.forgon.ru]}
    mode: development
    db_engine: mysqlidb
    db_charset: utf-8
    db_use_pconnection: 0
    db_host: localhost
    db_name: artisan
    db_user: root
    db_pass: 123456
    db_sql_mode: ''
    yandex:
      map: 'AKOG8E4BAAAALizHQwMAoN_aHuKG0-ZeeSolkZvKPCg2mdEAAAAAAAAAAABR6r4aeg6Y87XSpTpWgjr5vfissg==~AEnB8U4BAAAAfXjVAQIAdj4YN6uGLKDoLKF_kFGMOQxVDdMAAAAAAAAAAABWZkVWtEgDB8HNUOVnT0Ydi96-Lw=='
  anastasia:
    cond: {host: [nastya.artisan-dealers, www.nastya.artisan-dealers]}
    mode: development
    db_engine: mysql
    db_charset: utf-8
    db_use_pconnection: 0
    db_host: localhost
    db_name: artisan-dealers
    db_user: root
    db_pass: cnhjqrjdf_1
    db_sql_mode: ''
    yandex:
      map: 'AKOG8E4BAAAALizHQwMAoN_aHuKG0-ZeeSolkZvKPCg2mdEAAAAAAAAAAABR6r4aeg6Y87XSpTpWgjr5vfissg==~AEnB8U4BAAAAfXjVAQIAdj4YN6uGLKDoLKF_kFGMOQxVDdMAAAAAAAAAAABWZkVWtEgDB8HNUOVnT0Ydi96-Lw=='
  devel:
    cond: {host: [z.artisan-project.anna.devel, z.artisan-project.natasha.devel, z.artisan-project.mikhail.devel, z.artisan-project.le.devel]}
    mode: development
    db_engine: mysql
    db_charset: utf-8
    db_use_pconnection: 0
    db_host: 192.168.0.205
    db_name: artisan-project-dev
    db_user: artektiv
    db_pass: qazwsxedc
    db_sql_mode: ''
    yandex:
      map: 'AKOG8E4BAAAALizHQwMAoN_aHuKG0-ZeeSolkZvKPCg2mdEAAAAAAAAAAABR6r4aeg6Y87XSpTpWgjr5vfissg==~AEnB8U4BAAAAfXjVAQIAdj4YN6uGLKDoLKF_kFGMOQxVDdMAAAAAAAAAAABWZkVWtEgDB8HNUOVnT0Ydi96-Lw=='
  demo:
      cond: {host: [www.artisan-project.demo.artektiv.ru, artisan-project.demo.artektiv.ru]}
      mode: production
      db_engine: mysql
      db_charset: utf-8
      db_use_pconnection: 0
      db_host: localhost
      db_name: admin_artisanpr_db
      db_user: admin_artisanpr
      db_pass: yiah7OFbtU
      db_sql_mode: ''
      yandex:
        map: 'AKOG8E4BAAAALizHQwMAoN_aHuKG0-ZeeSolkZvKPCg2mdEAAAAAAAAAAABR6r4aeg6Y87XSpTpWgjr5vfissg==~AEnB8U4BAAAAfXjVAQIAdj4YN6uGLKDoLKF_kFGMOQxVDdMAAAAAAAAAAABWZkVWtEgDB8HNUOVnT0Ydi96-Lw=='
  remote: &remote
    cond: {}
    mode: production
    db_engine: mysql
    db_charset: utf-8
    db_use_pconnection: 0
#    db_host: u305676.mysql.masterhost.ru
#    db_name: u305676_apt
#    db_user: u305676_aptest
#    db_pass: 6in_A5eddEn-
    db_host: u261784.mysql.masterhost.ru
    db_name: u261784
    db_user: u261784
    db_pass: 3averoffi7
    yandex:
      map: 'AD3J8U4BAAAAtmXLFgIA16GE6GRdjd6GS54xXIEOTWZBCV4AAAAAAAAAAABrutC0HICJATowvCaUQi_qH5hH0Q=='
  default: *remote

# Different modes settings.
# In cond allowing following directives: host, ip, remote_ip. If no any matches found default_mode from Common settings will be used.
# error_reporting can be one of the following: E_ALL, E_ALL-E_NOTICE, '0' - quotes must not be omitted
modes:
  development:
    cond: 
      local: "*"
      anastasia: "*"
      forgon: "*"
      semen: "*"
      devel: *
    db_debug: {store_queries: 1, store_raw_queries: 1, store_results: 1, store_caller: 1, store_times: 1, times_precision: 5}
    debug: {error_reporting: E_ALL & ~E_STRICT & ~E_DEPRECATED, display_errors: 1, log_errors: 1, store_codesniplets: 1}
    smarty: {debug: 0}

  debug:
    cond:
      demo: {remote_ip: 83.229.142.164}
      remote: {remote_ip: 83.229.142.164}
      default: {remote_ip: 83.229.142.164}
    db_debug: {store_queries: 1, store_raw_queries: 1, store_results: 1, store_caller: 1, store_times: 1, times_precision: 5}
    debug: {error_reporting: E_ALL & ~E_STRICT & ~E_DEPRECATED, display_errors: 1, log_errors: 1, store_codesniplets: 1}
    smarty: {debug: 0}

  console:
    db_debug: {store_queries: 0, store_raw_queries: 0, store_results: 0, store_caller: 0, store_times: 0, times_precision: 0}
    debug: {error_reporting: E_ALL & ~E_STRICT & ~E_DEPRECATED, display_errors: 1, log_errors: 1, store_codesniplets: 0, disabled: 1}
    smarty: {debug: 0}

  production:
    cond:
      demo: "*"
      remote: "*"
    db_debug: {store_queries: 0, store_raw_queries: 0, store_results: 0, store_caller: 0, store_times: 0, times_precision: 0}
    debug: {error_reporting: E_ALL & ~E_STRICT & ~E_DEPRECATED, display_errors: 0, log_errors: 1, store_codesniplets: 0, disabled: 1}
    smarty: {debug: 0}

# Application parameters.
settings:
  show_remains: {title: Показывать остатки при поиске, type: checkbox, otitle: Показать, default: 'no', checked: 'yes'}
  op_refresh: {title: Время обновления страницы обработки заказов оператором (мин.), type: string}
  round_count: {title: 'Округление заказываемого дилерами, количества товара', type: checkbox, otitle: Округлять, default: 'no', checked: 'yes'}
  pwd_exp_dealer: {title: 'Срок действия пароля дилера(мес)', type: string}
  max_count_in_req: {title: 'Максимальное количесво позиций в заказе', type: string}
  total_price: {title: 'Минимальная сумма заказа', type: string}
  discount: {title: 'Общая скидка с сайта', type: string}
  account4extra_discount: {title: 'Сумма, превышая которую, начинает действовать дополнительная скидка', type: string}
  extra_discount: {title: Размер дополнительной скидки, type: string}
  extra_discount_text: {title: Текст для дополнительной скидки, type: text}
  banner_dealer_img: {title: 'Верхний банер для дилеров (изображение (300x90))', type: image}
  banner_dealer_url: {title: 'Верхний банер для дилеров (ссылка)', type: string}
  phone_code: {title: Телефонный код, type: string}
  phone: {title: Телефонный номер, type: string}
  address: {title: Адрес, type: string}
  email: {title: E-mail, type: raw_text}
  ship_time: {type: string, title: Время изменения ближайшей даты отгрузки}
  counters: {title: Счетчики, type: raw_text}
  blinked_action: {title: 'Мигающая кнопка "акция"', type: checkbox, default: 'no', checked: 'yes'}
  email_to_complaints: {title: E-mail для уведомлений о новых претензиях и новых комментариях дилеров, type: text}
  email_to_shipments: {title: E-mail для уведомлений о новых заявках на отгрузку, type: text}

  email_to_on_order: {title: E-mail для уведомлений о новых заказных заявках, type: text}
  type_answ: {title: Тип текста, type: string, default: 'text/html'}

  templ_answ: {title: '<strong>Шаблон письма уведомления об ответе на претензию:</strong> </br>', type: string, attrs: {style: 'width: 0px; height: 0px; border: 0px;'}}
  from_answ: {title: 'От', type: string, default: 'problema@artisan-project.ru'}
  subject_answ: {title: Тема, type: string, default: 'Ответ на Вашу претензию [reason_title]'}
  type_answ: {title: Тип текста, type: string, default: 'text/html'}
  message_answ:
    title: Текст письма
    type: ckhtml
    default: |
      Здесь вы можете посмотреть <a href="[complaint_link]">ответ</a> на вашу претензию.
  templ_compl: {title: '<strong>Шаблон письма уведомления о поступлении новых претензий:</strong> </br>', type: string, attrs: {style: 'width: 0px; height: 0px; border: 0px;'}}
  from_compl: {title: 'От', type: string, default: 'problema@artisan-project.ru'}
  subject_compl: {title: Тема, type: string, default: 'Поступила новая претензия [reason_title]'}
  type_compl: {title: Тип текста, type: string, default: 'text/html'}
  message_compl:
    title: Текст письма
    type: ckhtml
    default: |
      Поступила новая претензия: [reason_title].<br>
      От дилера: [company], [city], [user_name] [phone] [mail].<br>
      Текст претензии: [text]<br>
      Чтобы ответить на запрос перейдите  <a href="[complaint_link]">сюда</a>.
  templ_comm: {title: '<strong>Шаблон письма уведомления о поступлении новых сообщений по претензии:</strong> </br>', type: string, attrs: {style: 'width: 0px; height: 0px; border: 0px;'}}
  from_comm: {title: 'От', type: string, default: 'problema@artisan-project.ru'}
  subject_comm: {title: Тема, type: string, default: 'Поступило новое сообщение по претензии [reason_title]'}
  type_comm: {title: Тип текста, type: string, default: 'text/html'}
  euro_rub: {title: Курс евро, type: float, default: ''}
  message_comm:
    title: Текст письма
    type: ckhtml
    default: |
      Поступило новое сообщение по претензии: [reason_title].<br>
      Текст претензии: [text]<br>
      Чтобы ответить на запрос перейдите  <a href="[complaint_link]">сюда</a>.

# Меню CMS
cms_menu:
  - title: Страницы
    link: content
    icon: content
    submenu:
      - title: Показать страницы
        link: content/list
      - title: Редактировать главную
        link: content/modify/id/1/pid/1
      - hr
      - title: Баннеры
        link: banners
  - title: Новости
    link: news
  - title: Каталог
    submenu:
      - title: Фабрики
        link: catalog/list_factories
      - title: Коллекции
        link: catalog/list_collections
      - title: Товары
        link: catalog/list_goods
      - title: Товары на заказ
        link: catalog/list_goods_to_order
      - title: Рекламная продукция
        link: catalog/list_promotional
      - hr
      - title: Страны
        link: catalog/list_countries
      - title: Типы
        link: catalog/list_types
      - title: Назначения
        link: catalog/list_purposes
      - title: Поверхности
        link: catalog/list_surfaces
      - title: Стили
        link: catalog/list_styles		
      - title: Цвета
        link: catalog/list_colors		
      - title: Материалы
        link: catalog/list_materials
      - title: Виды рекламной продукции
        link: catalog/list_typespromotional
      - hr
      - title: База данных
        link: db
      - title: Журнал импорта
        link: logs/list_import
  - title: Меню
    submenu:
      - title: Верхнее меню
        link: menu/list_top_menu
      - title: Нижнее меню
        link: menu/list_bottom_menu
  - title: Документы
    link: documents
    submenu:
      - title: Папки
        link: documents/list_documents_folders/id/1
  - title: Мерчандайзинг
    link: db/list_merchandising_elements
    submenu:
      - title: Генеральный каталог
        link: db/modify_merch_main_catalog/id/1
      - title: Типы
        link: db/list_merchandising_types
  - title: Прайс-лист
    link: db/list_price_lists
    submenu:
      - title: Информация по последней переоценке
        link: db/modify_info_last/id/1
  - title: Статистика
    link: stats
    submenu:
      - title: Активность дилеров
        link: stats/dealers
      - title: Лучший товар
        link: stats/best_goods
  - title: Сотрудники
    link: employees
    submenu:
      - title: Отделы
        link: employees/list_employees_otdels
# - title: Сообщения
#   link: messages
  - title: Доставка
    link: delivery
    submenu:
      - title: Редактировать свойства зон доставок
        link: delivery/list
  - title: Заявки
    link: requests
    submenu:
      - title: Статусы
        link: requests/list_requests_statuses
      - title: Способы оплаты для ОптМаг
        link: requests/list_payment_methods
  - title: Заявки(под заказ)
    link: requests/list_requests_to_order
  - title: Отгрузки
    link: shipment
    submenu:
      - title: Типы отгрузок
        link: shipment/list_shipment_types
      - title: Виды подготовки товара
        link: shipment/list_shipment_preps
      - title: Транспортные компании
        link: shipment/list_transport_companies
      - title: Настройка времени
        link: shipment/modify_shipment_times/id/1
  - title: Претензии
    link: complaints
    submenu:
      - title: Причины обращения
        link: complaints/list_reasons
cms_smenu:
  - title: Администраторы
    link: users
    submenu:
      - title: Добавить
        link: users/add
      - hr
      - title: Роли
        link: users/list_roles
      - title: Добавить роль
        link: users/add_role
  - title: Операторы
    link: operators
  - title: Блок сообщений
    link: db/list_message_blocks	
  - title: Дилеры
    link: dealers
    submenu:
      - title: Просмотреть дилеров
        link: dealers/list_dealers
      - title: Добавить дилера
        link: dealers/add_dealer
      - hr
      - title: Просмотреть категории
        link: dealers/list_categories
      - title: Добавить категорию
        link: dealers/add_category
      - hr
      - title: Просмотреть поставщиков
        link: dealers/list_suppliers
      - title: Добавить поставщика
        link: dealers/add_supplier
  - title: Контакты
    link: employees/list_employees_contacts
    submenu:
      - title: Отделы
        link: employees/list_contacts
  - title: Изображения
    link: images
  - title: Раздел "О компании"
    submenu:
      - title: Блок "Наши клиенты"
        link: banners/list_about_clients
      - title: Текстовые блоки
        link: db/list_text_blocks
      - title: Блок "Наши партнёры"
        link: banners/list_about_partners
      - title: Блок "Благодарственные письма"
        link: banners/list_about_sertificates
      - title: Реквизиты
        link: db/list_rekvisites
      - title: Банковские реквизиты
        link: db/list_bank_rekvisites
      - title: Документы
        link: banners/list_about_docs
      - title: Фотогалерея
        link: banners/list_about_fotogallery
  - title: Слайдер на главной
    link: banners/list_main_slider
	