<?php

/**
 * This file is generated by Fork CMS, it contains
 * more information about the page-structure
 * 
 * Fork CMS
 * @generated	2014-12-06 21:22:53
 */

// init var
$navigation = array();

$navigation['footer'][0][2]['page_id'] = 2;
$navigation['footer'][0][2]['url'] = 'karta-saita';
$navigation['footer'][0][2]['full_url'] = '/karta-saita';
$navigation['footer'][0][2]['title'] = 'Карта сайта';
$navigation['footer'][0][2]['navigation_title'] = 'Карта сайта';
$navigation['footer'][0][2]['has_extra'] = false;
$navigation['footer'][0][2]['no_follow'] = false;
$navigation['footer'][0][2]['hidden'] = false;
$navigation['footer'][0][2]['extra_blocks'] = null;
$navigation['footer'][0][2]['tree_type'] = 'sitemap';

$navigation['footer'][0][3]['page_id'] = 3;
$navigation['footer'][0][3]['url'] = 'soghlashieniie';
$navigation['footer'][0][3]['full_url'] = '/soghlashieniie';
$navigation['footer'][0][3]['title'] = 'Соглашение';
$navigation['footer'][0][3]['navigation_title'] = 'Соглашение';
$navigation['footer'][0][3]['has_extra'] = false;
$navigation['footer'][0][3]['no_follow'] = true;
$navigation['footer'][0][3]['hidden'] = false;
$navigation['footer'][0][3]['extra_blocks'] = null;
$navigation['footer'][0][3]['tree_type'] = 'page';

$navigation['root'][0][404]['page_id'] = 404;
$navigation['root'][0][404]['url'] = '404';
$navigation['root'][0][404]['full_url'] = '/404';
$navigation['root'][0][404]['title'] = '404';
$navigation['root'][0][404]['navigation_title'] = '404';
$navigation['root'][0][404]['has_extra'] = false;
$navigation['root'][0][404]['no_follow'] = false;
$navigation['root'][0][404]['hidden'] = false;
$navigation['root'][0][404]['extra_blocks'] = null;
$navigation['root'][0][404]['tree_type'] = 'error';

$navigation['root'][0][410]['page_id'] = 410;
$navigation['root'][0][410]['url'] = 'lorem-ipsum';
$navigation['root'][0][410]['full_url'] = '/lorem-ipsum';
$navigation['root'][0][410]['title'] = 'Lorem ipsum';
$navigation['root'][0][410]['navigation_title'] = 'Lorem ipsum';
$navigation['root'][0][410]['has_extra'] = false;
$navigation['root'][0][410]['no_follow'] = true;
$navigation['root'][0][410]['hidden'] = true;
$navigation['root'][0][410]['extra_blocks'] = null;
$navigation['root'][0][410]['tree_type'] = 'hidden';

$navigation['root'][0][411]['page_id'] = 411;
$navigation['root'][0][411]['url'] = 'poisk';
$navigation['root'][0][411]['full_url'] = '/poisk';
$navigation['root'][0][411]['title'] = 'Поиск';
$navigation['root'][0][411]['navigation_title'] = 'Поиск';
$navigation['root'][0][411]['has_extra'] = true;
$navigation['root'][0][411]['no_follow'] = false;
$navigation['root'][0][411]['hidden'] = false;
$navigation['root'][0][411]['extra_blocks'] = array(array('id' => 2, 'module' => 'Search', 'action' => null));
$navigation['root'][0][411]['tree_type'] = 'page';

$navigation['root'][0][412]['page_id'] = 412;
$navigation['root'][0][412]['url'] = 'tags';
$navigation['root'][0][412]['full_url'] = '/tags';
$navigation['root'][0][412]['title'] = 'Tags';
$navigation['root'][0][412]['navigation_title'] = 'Tags';
$navigation['root'][0][412]['has_extra'] = true;
$navigation['root'][0][412]['no_follow'] = false;
$navigation['root'][0][412]['hidden'] = false;
$navigation['root'][0][412]['extra_blocks'] = array(array('id' => 12, 'module' => 'Tags', 'action' => null));
$navigation['root'][0][412]['tree_type'] = 'page';

$navigation['root'][0][415]['page_id'] = 415;
$navigation['root'][0][415]['url'] = 'razoslannyie-rassylki';
$navigation['root'][0][415]['full_url'] = '/razoslannyie-rassylki';
$navigation['root'][0][415]['title'] = 'Разосланные рассылки';
$navigation['root'][0][415]['navigation_title'] = 'Разосланные рассылки';
$navigation['root'][0][415]['has_extra'] = true;
$navigation['root'][0][415]['no_follow'] = false;
$navigation['root'][0][415]['hidden'] = false;
$navigation['root'][0][415]['extra_blocks'] = array(array('id' => 21, 'module' => 'Mailmotor', 'action' => null));
$navigation['root'][0][415]['tree_type'] = 'page';

$navigation['root'][0][418]['page_id'] = 418;
$navigation['root'][0][418]['url'] = 'activate';
$navigation['root'][0][418]['full_url'] = '/activate';
$navigation['root'][0][418]['title'] = 'Activate';
$navigation['root'][0][418]['navigation_title'] = 'Activate';
$navigation['root'][0][418]['has_extra'] = true;
$navigation['root'][0][418]['no_follow'] = false;
$navigation['root'][0][418]['hidden'] = false;
$navigation['root'][0][418]['extra_blocks'] = array(array('id' => 25, 'module' => 'Profiles', 'action' => 'Activate'));
$navigation['root'][0][418]['tree_type'] = 'page';

$navigation['root'][0][419]['page_id'] = 419;
$navigation['root'][0][419]['url'] = 'forgot-password';
$navigation['root'][0][419]['full_url'] = '/forgot-password';
$navigation['root'][0][419]['title'] = 'Forgot password';
$navigation['root'][0][419]['navigation_title'] = 'Forgot password';
$navigation['root'][0][419]['has_extra'] = true;
$navigation['root'][0][419]['no_follow'] = false;
$navigation['root'][0][419]['hidden'] = false;
$navigation['root'][0][419]['extra_blocks'] = array(array('id' => 26, 'module' => 'Profiles', 'action' => 'ForgotPassword'));
$navigation['root'][0][419]['tree_type'] = 'page';

$navigation['root'][0][420]['page_id'] = 420;
$navigation['root'][0][420]['url'] = 'reset-password';
$navigation['root'][0][420]['full_url'] = '/reset-password';
$navigation['root'][0][420]['title'] = 'Reset password';
$navigation['root'][0][420]['navigation_title'] = 'Reset password';
$navigation['root'][0][420]['has_extra'] = true;
$navigation['root'][0][420]['no_follow'] = false;
$navigation['root'][0][420]['hidden'] = false;
$navigation['root'][0][420]['extra_blocks'] = array(array('id' => 34, 'module' => 'Profiles', 'action' => 'ResetPassword'));
$navigation['root'][0][420]['tree_type'] = 'page';

$navigation['root'][0][421]['page_id'] = 421;
$navigation['root'][0][421]['url'] = 'resend-activation-e-mail';
$navigation['root'][0][421]['full_url'] = '/resend-activation-e-mail';
$navigation['root'][0][421]['title'] = 'Resend activation e-mail';
$navigation['root'][0][421]['navigation_title'] = 'Resend activation e-mail';
$navigation['root'][0][421]['has_extra'] = true;
$navigation['root'][0][421]['no_follow'] = false;
$navigation['root'][0][421]['hidden'] = false;
$navigation['root'][0][421]['extra_blocks'] = array(array('id' => 35, 'module' => 'Profiles', 'action' => 'ResendActivation'));
$navigation['root'][0][421]['tree_type'] = 'page';

$navigation['root'][0][422]['page_id'] = 422;
$navigation['root'][0][422]['url'] = 'login';
$navigation['root'][0][422]['full_url'] = '/login';
$navigation['root'][0][422]['title'] = 'Login';
$navigation['root'][0][422]['navigation_title'] = 'Login';
$navigation['root'][0][422]['has_extra'] = true;
$navigation['root'][0][422]['no_follow'] = false;
$navigation['root'][0][422]['hidden'] = false;
$navigation['root'][0][422]['extra_blocks'] = array(array('id' => 28, 'module' => 'Profiles', 'action' => 'Login'));
$navigation['root'][0][422]['tree_type'] = 'page';

$navigation['root'][0][423]['page_id'] = 423;
$navigation['root'][0][423]['url'] = 'register';
$navigation['root'][0][423]['full_url'] = '/register';
$navigation['root'][0][423]['title'] = 'Register';
$navigation['root'][0][423]['navigation_title'] = 'Register';
$navigation['root'][0][423]['has_extra'] = true;
$navigation['root'][0][423]['no_follow'] = false;
$navigation['root'][0][423]['hidden'] = false;
$navigation['root'][0][423]['extra_blocks'] = array(array('id' => 33, 'module' => 'Profiles', 'action' => 'Register'));
$navigation['root'][0][423]['tree_type'] = 'page';

$navigation['root'][0][424]['page_id'] = 424;
$navigation['root'][0][424]['url'] = 'logout';
$navigation['root'][0][424]['full_url'] = '/logout';
$navigation['root'][0][424]['title'] = 'Logout';
$navigation['root'][0][424]['navigation_title'] = 'Logout';
$navigation['root'][0][424]['has_extra'] = true;
$navigation['root'][0][424]['no_follow'] = false;
$navigation['root'][0][424]['hidden'] = false;
$navigation['root'][0][424]['extra_blocks'] = array(array('id' => 29, 'module' => 'Profiles', 'action' => 'Logout'));
$navigation['root'][0][424]['tree_type'] = 'page';

$navigation['root'][0][425]['page_id'] = 425;
$navigation['root'][0][425]['url'] = 'profile';
$navigation['root'][0][425]['full_url'] = '/profile';
$navigation['root'][0][425]['title'] = 'Profile';
$navigation['root'][0][425]['navigation_title'] = 'Profile';
$navigation['root'][0][425]['has_extra'] = true;
$navigation['root'][0][425]['no_follow'] = false;
$navigation['root'][0][425]['hidden'] = false;
$navigation['root'][0][425]['extra_blocks'] = array(array('id' => 27, 'module' => 'Profiles', 'action' => null));
$navigation['root'][0][425]['tree_type'] = 'page';

$navigation['page'][0][1]['page_id'] = 1;
$navigation['page'][0][1]['url'] = '';
$navigation['page'][0][1]['full_url'] = '/';
$navigation['page'][0][1]['title'] = 'Главная';
$navigation['page'][0][1]['navigation_title'] = 'Главная';
$navigation['page'][0][1]['has_extra'] = false;
$navigation['page'][0][1]['no_follow'] = false;
$navigation['page'][0][1]['hidden'] = false;
$navigation['page'][0][1]['extra_blocks'] = null;
$navigation['page'][0][1]['tree_type'] = 'direct_action';

$navigation['page'][1][405]['page_id'] = 405;
$navigation['page'][1][405]['url'] = 'blogh';
$navigation['page'][1][405]['full_url'] = '/blogh';
$navigation['page'][1][405]['title'] = 'Блог';
$navigation['page'][1][405]['navigation_title'] = 'Блог';
$navigation['page'][1][405]['has_extra'] = true;
$navigation['page'][1][405]['no_follow'] = false;
$navigation['page'][1][405]['hidden'] = false;
$navigation['page'][1][405]['extra_blocks'] = array(array('id' => 6, 'module' => 'Blog', 'action' => null));
$navigation['page'][1][405]['tree_type'] = 'page';

$navigation['page'][1][406]['page_id'] = 406;
$navigation['page'][1][406]['url'] = 'o-nas';
$navigation['page'][1][406]['full_url'] = '/o-nas';
$navigation['page'][1][406]['title'] = 'О нас';
$navigation['page'][1][406]['navigation_title'] = 'О нас';
$navigation['page'][1][406]['has_extra'] = false;
$navigation['page'][1][406]['no_follow'] = false;
$navigation['page'][1][406]['hidden'] = false;
$navigation['page'][1][406]['extra_blocks'] = null;
$navigation['page'][1][406]['tree_type'] = 'page';

$navigation['page'][1][409]['page_id'] = 409;
$navigation['page'][1][409]['url'] = 'istoriia';
$navigation['page'][1][409]['full_url'] = '/istoriia';
$navigation['page'][1][409]['title'] = 'История';
$navigation['page'][1][409]['navigation_title'] = 'История';
$navigation['page'][1][409]['has_extra'] = false;
$navigation['page'][1][409]['no_follow'] = false;
$navigation['page'][1][409]['hidden'] = false;
$navigation['page'][1][409]['extra_blocks'] = null;
$navigation['page'][1][409]['tree_type'] = 'page';

$navigation['page'][1][413]['page_id'] = 413;
$navigation['page'][1][413]['url'] = 'faq';
$navigation['page'][1][413]['full_url'] = '/faq';
$navigation['page'][1][413]['title'] = 'FAQ';
$navigation['page'][1][413]['navigation_title'] = 'FAQ';
$navigation['page'][1][413]['has_extra'] = true;
$navigation['page'][1][413]['no_follow'] = false;
$navigation['page'][1][413]['hidden'] = false;
$navigation['page'][1][413]['extra_blocks'] = array(array('id' => 15, 'module' => 'Faq', 'action' => null));
$navigation['page'][1][413]['tree_type'] = 'page';

$navigation['page'][1][414]['page_id'] = 414;
$navigation['page'][1][414]['url'] = 'kontakt';
$navigation['page'][1][414]['full_url'] = '/kontakt';
$navigation['page'][1][414]['title'] = 'Контакт';
$navigation['page'][1][414]['navigation_title'] = 'Контакт';
$navigation['page'][1][414]['has_extra'] = false;
$navigation['page'][1][414]['no_follow'] = false;
$navigation['page'][1][414]['hidden'] = false;
$navigation['page'][1][414]['extra_blocks'] = null;
$navigation['page'][1][414]['tree_type'] = 'page';

$navigation['page'][1][430]['page_id'] = 430;
$navigation['page'][1][430]['url'] = 'automatisation';
$navigation['page'][1][430]['full_url'] = '/automatisation';
$navigation['page'][1][430]['title'] = 'Автоматизация';
$navigation['page'][1][430]['navigation_title'] = 'Автоматизация';
$navigation['page'][1][430]['has_extra'] = false;
$navigation['page'][1][430]['no_follow'] = false;
$navigation['page'][1][430]['hidden'] = false;
$navigation['page'][1][430]['extra_blocks'] = null;
$navigation['page'][1][430]['tree_type'] = 'page';

$navigation['page'][1][433]['page_id'] = 433;
$navigation['page'][1][433]['url'] = 'web';
$navigation['page'][1][433]['full_url'] = '/web';
$navigation['page'][1][433]['title'] = 'Веб';
$navigation['page'][1][433]['navigation_title'] = 'Веб';
$navigation['page'][1][433]['has_extra'] = false;
$navigation['page'][1][433]['no_follow'] = false;
$navigation['page'][1][433]['hidden'] = false;
$navigation['page'][1][433]['extra_blocks'] = null;
$navigation['page'][1][433]['tree_type'] = 'page';

$navigation['page'][1][439]['page_id'] = 439;
$navigation['page'][1][439]['url'] = 'it-soprovozhdieniie';
$navigation['page'][1][439]['full_url'] = '/it-soprovozhdieniie';
$navigation['page'][1][439]['title'] = 'IT-сопровождение';
$navigation['page'][1][439]['navigation_title'] = 'IT-сопровождение';
$navigation['page'][1][439]['has_extra'] = false;
$navigation['page'][1][439]['no_follow'] = false;
$navigation['page'][1][439]['hidden'] = false;
$navigation['page'][1][439]['extra_blocks'] = null;
$navigation['page'][1][439]['tree_type'] = 'page';

$navigation['page'][415][416]['page_id'] = 416;
$navigation['page'][415][416]['url'] = 'podpiska';
$navigation['page'][415][416]['full_url'] = '/razoslannyie-rassylki/podpiska';
$navigation['page'][415][416]['title'] = 'Подписка';
$navigation['page'][415][416]['navigation_title'] = 'Подписка';
$navigation['page'][415][416]['has_extra'] = true;
$navigation['page'][415][416]['no_follow'] = false;
$navigation['page'][415][416]['hidden'] = false;
$navigation['page'][415][416]['extra_blocks'] = array(array('id' => 22, 'module' => 'Mailmotor', 'action' => 'Subscribe'));
$navigation['page'][415][416]['tree_type'] = 'page';

$navigation['page'][415][417]['page_id'] = 417;
$navigation['page'][415][417]['url'] = 'otpisat-sia';
$navigation['page'][415][417]['full_url'] = '/razoslannyie-rassylki/otpisat-sia';
$navigation['page'][415][417]['title'] = 'Отписаться';
$navigation['page'][415][417]['navigation_title'] = 'Отписаться';
$navigation['page'][415][417]['has_extra'] = true;
$navigation['page'][415][417]['no_follow'] = false;
$navigation['page'][415][417]['hidden'] = false;
$navigation['page'][415][417]['extra_blocks'] = array(array('id' => 23, 'module' => 'Mailmotor', 'action' => 'Unsubscribe'));
$navigation['page'][415][417]['tree_type'] = 'page';

$navigation['page'][425][426]['page_id'] = 426;
$navigation['page'][425][426]['url'] = 'profile-settings';
$navigation['page'][425][426]['full_url'] = '/profile/profile-settings';
$navigation['page'][425][426]['title'] = 'Profile settings';
$navigation['page'][425][426]['navigation_title'] = 'Profile settings';
$navigation['page'][425][426]['has_extra'] = true;
$navigation['page'][425][426]['no_follow'] = false;
$navigation['page'][425][426]['hidden'] = false;
$navigation['page'][425][426]['extra_blocks'] = array(array('id' => 32, 'module' => 'Profiles', 'action' => 'Settings'));
$navigation['page'][425][426]['tree_type'] = 'page';

$navigation['page'][425][427]['page_id'] = 427;
$navigation['page'][425][427]['url'] = 'change-email';
$navigation['page'][425][427]['full_url'] = '/profile/change-email';
$navigation['page'][425][427]['title'] = 'Change email';
$navigation['page'][425][427]['navigation_title'] = 'Change email';
$navigation['page'][425][427]['has_extra'] = true;
$navigation['page'][425][427]['no_follow'] = false;
$navigation['page'][425][427]['hidden'] = false;
$navigation['page'][425][427]['extra_blocks'] = array(array('id' => 30, 'module' => 'Profiles', 'action' => 'ChangeEmail'));
$navigation['page'][425][427]['tree_type'] = 'page';

$navigation['page'][425][428]['page_id'] = 428;
$navigation['page'][425][428]['url'] = 'change-password';
$navigation['page'][425][428]['full_url'] = '/profile/change-password';
$navigation['page'][425][428]['title'] = 'Change password';
$navigation['page'][425][428]['navigation_title'] = 'Change password';
$navigation['page'][425][428]['has_extra'] = true;
$navigation['page'][425][428]['no_follow'] = false;
$navigation['page'][425][428]['hidden'] = false;
$navigation['page'][425][428]['extra_blocks'] = array(array('id' => 31, 'module' => 'Profiles', 'action' => 'ChangePassword'));
$navigation['page'][425][428]['tree_type'] = 'page';

$navigation['page'][406][407]['page_id'] = 407;
$navigation['page'][406][407]['url'] = 'miestopolozhieniie';
$navigation['page'][406][407]['full_url'] = '/o-nas/miestopolozhieniie';
$navigation['page'][406][407]['title'] = 'Местоположение';
$navigation['page'][406][407]['navigation_title'] = 'Местоположение';
$navigation['page'][406][407]['has_extra'] = false;
$navigation['page'][406][407]['no_follow'] = false;
$navigation['page'][406][407]['hidden'] = false;
$navigation['page'][406][407]['extra_blocks'] = null;
$navigation['page'][406][407]['tree_type'] = 'page';

$navigation['page'][406][408]['page_id'] = 408;
$navigation['page'][406][408]['url'] = 'o-nas';
$navigation['page'][406][408]['full_url'] = '/o-nas/o-nas';
$navigation['page'][406][408]['title'] = 'О нас';
$navigation['page'][406][408]['navigation_title'] = 'О нас';
$navigation['page'][406][408]['has_extra'] = false;
$navigation['page'][406][408]['no_follow'] = false;
$navigation['page'][406][408]['hidden'] = false;
$navigation['page'][406][408]['extra_blocks'] = null;
$navigation['page'][406][408]['tree_type'] = 'page';

$navigation['page'][430][429]['page_id'] = 429;
$navigation['page'][430][429]['url'] = '71-buh';
$navigation['page'][430][429]['full_url'] = '/automatisation/71-buh';
$navigation['page'][430][429]['title'] = 'Автоматизация бухгалтерии';
$navigation['page'][430][429]['navigation_title'] = 'Автоматизация бухгалтерии';
$navigation['page'][430][429]['has_extra'] = false;
$navigation['page'][430][429]['no_follow'] = false;
$navigation['page'][430][429]['hidden'] = false;
$navigation['page'][430][429]['extra_blocks'] = null;
$navigation['page'][430][429]['tree_type'] = 'page';

$navigation['page'][430][431]['page_id'] = 431;
$navigation['page'][430][431]['url'] = '72-zar';
$navigation['page'][430][431]['full_url'] = '/automatisation/72-zar';
$navigation['page'][430][431]['title'] = 'Автоматизация зарплаты';
$navigation['page'][430][431]['navigation_title'] = 'Автоматизация зарплаты';
$navigation['page'][430][431]['has_extra'] = false;
$navigation['page'][430][431]['no_follow'] = false;
$navigation['page'][430][431]['hidden'] = false;
$navigation['page'][430][431]['extra_blocks'] = null;
$navigation['page'][430][431]['tree_type'] = 'page';

$navigation['page'][433][432]['page_id'] = 432;
$navigation['page'][433][432]['url'] = '81-seo';
$navigation['page'][433][432]['full_url'] = '/web/81-seo';
$navigation['page'][433][432]['title'] = 'Продвижение сайтов (SEO)';
$navigation['page'][433][432]['navigation_title'] = 'Продвижение сайтов (SEO)';
$navigation['page'][433][432]['has_extra'] = false;
$navigation['page'][433][432]['no_follow'] = false;
$navigation['page'][433][432]['hidden'] = false;
$navigation['page'][433][432]['extra_blocks'] = null;
$navigation['page'][433][432]['tree_type'] = 'page';

$navigation['page'][433][434]['page_id'] = 434;
$navigation['page'][433][434]['url'] = 'sozdaniie-saitov';
$navigation['page'][433][434]['full_url'] = '/web/sozdaniie-saitov';
$navigation['page'][433][434]['title'] = 'Создание сайтов';
$navigation['page'][433][434]['navigation_title'] = 'Создание сайтов';
$navigation['page'][433][434]['has_extra'] = false;
$navigation['page'][433][434]['no_follow'] = false;
$navigation['page'][433][434]['hidden'] = false;
$navigation['page'][433][434]['extra_blocks'] = null;
$navigation['page'][433][434]['tree_type'] = 'page';

$navigation['page'][433][438]['page_id'] = 438;
$navigation['page'][433][438]['url'] = 'vieb-dizain';
$navigation['page'][433][438]['full_url'] = '/web/vieb-dizain';
$navigation['page'][433][438]['title'] = 'Веб-дизайн';
$navigation['page'][433][438]['navigation_title'] = 'Веб-дизайн';
$navigation['page'][433][438]['has_extra'] = false;
$navigation['page'][433][438]['no_follow'] = false;
$navigation['page'][433][438]['hidden'] = false;
$navigation['page'][433][438]['extra_blocks'] = null;
$navigation['page'][433][438]['tree_type'] = 'page';

$navigation['page'][439][440]['page_id'] = 440;
$navigation['page'][439][440]['url'] = 'vniedrieniie';
$navigation['page'][439][440]['full_url'] = '/it-soprovozhdieniie/vniedrieniie';
$navigation['page'][439][440]['title'] = 'Внедрение';
$navigation['page'][439][440]['navigation_title'] = 'Внедрение';
$navigation['page'][439][440]['has_extra'] = false;
$navigation['page'][439][440]['no_follow'] = false;
$navigation['page'][439][440]['hidden'] = false;
$navigation['page'][439][440]['extra_blocks'] = null;
$navigation['page'][439][440]['tree_type'] = 'page';

$navigation['page'][439][442]['page_id'] = 442;
$navigation['page'][439][442]['url'] = 'poddierzhka';
$navigation['page'][439][442]['full_url'] = '/it-soprovozhdieniie/poddierzhka';
$navigation['page'][439][442]['title'] = 'Поддержка';
$navigation['page'][439][442]['navigation_title'] = 'Поддержка';
$navigation['page'][439][442]['has_extra'] = false;
$navigation['page'][439][442]['no_follow'] = false;
$navigation['page'][439][442]['hidden'] = false;
$navigation['page'][439][442]['extra_blocks'] = null;
$navigation['page'][439][442]['tree_type'] = 'page';

$navigation['page'][439][444]['page_id'] = 444;
$navigation['page'][439][444]['url'] = 'obuchieniie';
$navigation['page'][439][444]['full_url'] = '/it-soprovozhdieniie/obuchieniie';
$navigation['page'][439][444]['title'] = 'Обучение';
$navigation['page'][439][444]['navigation_title'] = 'Обучение';
$navigation['page'][439][444]['has_extra'] = false;
$navigation['page'][439][444]['no_follow'] = false;
$navigation['page'][439][444]['hidden'] = false;
$navigation['page'][439][444]['extra_blocks'] = null;
$navigation['page'][439][444]['tree_type'] = 'page';

$navigation['page'][434][435]['page_id'] = 435;
$navigation['page'][434][435]['url'] = 'korporativnyi-sait';
$navigation['page'][434][435]['full_url'] = '/web/sozdaniie-saitov/korporativnyi-sait';
$navigation['page'][434][435]['title'] = 'Корпоративный сайт';
$navigation['page'][434][435]['navigation_title'] = 'Корпоративный сайт';
$navigation['page'][434][435]['has_extra'] = false;
$navigation['page'][434][435]['no_follow'] = false;
$navigation['page'][434][435]['hidden'] = false;
$navigation['page'][434][435]['extra_blocks'] = null;
$navigation['page'][434][435]['tree_type'] = 'page';

$navigation['page'][434][436]['page_id'] = 436;
$navigation['page'][434][436]['url'] = 'sait-vizitka';
$navigation['page'][434][436]['full_url'] = '/web/sozdaniie-saitov/sait-vizitka';
$navigation['page'][434][436]['title'] = 'Сайт-визитка';
$navigation['page'][434][436]['navigation_title'] = 'Сайт-визитка';
$navigation['page'][434][436]['has_extra'] = false;
$navigation['page'][434][436]['no_follow'] = false;
$navigation['page'][434][436]['hidden'] = false;
$navigation['page'][434][436]['extra_blocks'] = null;
$navigation['page'][434][436]['tree_type'] = 'page';

$navigation['page'][434][437]['page_id'] = 437;
$navigation['page'][434][437]['url'] = 'intierniet-maghazin';
$navigation['page'][434][437]['full_url'] = '/web/sozdaniie-saitov/intierniet-maghazin';
$navigation['page'][434][437]['title'] = 'Интернет-магазин';
$navigation['page'][434][437]['navigation_title'] = 'Интернет-магазин';
$navigation['page'][434][437]['has_extra'] = false;
$navigation['page'][434][437]['no_follow'] = false;
$navigation['page'][434][437]['hidden'] = false;
$navigation['page'][434][437]['extra_blocks'] = null;
$navigation['page'][434][437]['tree_type'] = 'page';

$navigation['page'][442][441]['page_id'] = 441;
$navigation['page'][442][441]['url'] = 'poddierzhka-fizichieskikh-lits';
$navigation['page'][442][441]['full_url'] = '/it-soprovozhdieniie/poddierzhka/poddierzhka-fizichieskikh-lits';
$navigation['page'][442][441]['title'] = 'Поддержка физических лиц';
$navigation['page'][442][441]['navigation_title'] = 'Поддержка физических лиц';
$navigation['page'][442][441]['has_extra'] = false;
$navigation['page'][442][441]['no_follow'] = false;
$navigation['page'][442][441]['hidden'] = false;
$navigation['page'][442][441]['extra_blocks'] = null;
$navigation['page'][442][441]['tree_type'] = 'page';

$navigation['page'][442][443]['page_id'] = 443;
$navigation['page'][442][443]['url'] = 'poddierzhka-iuridichieskikh-lits';
$navigation['page'][442][443]['full_url'] = '/it-soprovozhdieniie/poddierzhka/poddierzhka-iuridichieskikh-lits';
$navigation['page'][442][443]['title'] = 'Поддержка юридических лиц';
$navigation['page'][442][443]['navigation_title'] = 'Поддержка юридических лиц';
$navigation['page'][442][443]['has_extra'] = false;
$navigation['page'][442][443]['no_follow'] = false;
$navigation['page'][442][443]['hidden'] = false;
$navigation['page'][442][443]['extra_blocks'] = null;
$navigation['page'][442][443]['tree_type'] = 'page';

?>