<?
$arUrlRewrite = array(
	array(
		"CONDITION" => "#^/gallery/alla-maslennikova/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/gallery/alla-maslennikova/index.php",
	),
	array(
		"CONDITION" => "#^/site_mp/personal/order/#",
		"RULE" => "",
		"ID" => "bitrix:sale.personal.order",
		"PATH" => "/site_mp/personal/order/index.php",
	),
	array(
		"CONDITION" => "#^/site_mp/company/staff/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/site_mp/company/staff/index.php",
	),
	array(
		"CONDITION" => "#^/en/info/master-klass/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/en/info/master-klass/index.php",
	),
	array(
		"CONDITION" => "#^/site_mp/info/article/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/site_mp/info/article/index.php",
	),
	array(
		"CONDITION" => "#^/site_mp/company/news/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/site_mp/company/news/index.php",
	),
	array(
		"CONDITION" => "#^/site_mp/info/video/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/site_mp/info/video/index.php",
	),
	array(
		"CONDITION" => "#^/site_mp/info/brand/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/site_mp/info/brand/index.php",
	),
	array(
		"CONDITION" => "#^/en/personal/order/#",
		"RULE" => "",
		"ID" => "bitrix:sale.personal.order",
		"PATH" => "/en/personal/order/index.php",
	),
	array(
		"CONDITION" => "#^/info/master-klass/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/info/master-klass/index.php",
	),
	array(
		"CONDITION" => "#^/en/company/staff/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/en/company/staff/index.php",
	),
	array(
		"CONDITION" => "#^/en/info/gallery/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/en/info/gallery/index.php",
	),
	array(
		"CONDITION" => "#^/site_mp/catalog/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/site_mp/catalog/index.php",
	),
	array(
		"CONDITION" => "#^/en/company/news/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/en/company/news/index.php",
	),
	array(
		"CONDITION" => "#^/en/info/article/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/en/info/article/index.php",
	),
	array(
		"CONDITION" => "#^/personal/order/#",
		"RULE" => "",
		"ID" => "bitrix:sale.personal.order",
		"PATH" => "/personal/order/index.php",
	),
	array(
		"CONDITION" => "#^/site_mp/stores/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/site_mp/stores/index.php",
	),
	array(
		"CONDITION" => "#^/company/staff/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/company/staff/index.php",
	),
	array(
		"CONDITION" => "#^/en/info/brand/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/en/info/brand/index.php",
	),
	array(
		"CONDITION" => "#^/en/info/video/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/en/info/video/index.php",
	),
	array(
		"CONDITION" => "#^/company/news/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/company/news/index.php",
	),
	array(
		"CONDITION" => "#^/site_mp/news/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/site_mp/news/index.php",
	),
	array(
		"CONDITION" => "#^/site_mp/sale/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/site_mp/sale/index.php",
	),
	array(
		"CONDITION" => "#^/info/gallery/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/info/gallery/index.php",
	),
	array(
		"CONDITION" => "#^/info/article/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/info/article/index.php",
	),
	array(
		"CONDITION" => "#^/info/brand/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/info/brand/index.php",
	),
	array(
		"CONDITION" => "#^/en/catalog/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/en/catalog/index.php",
	),
	array(
		"CONDITION" => "#^/en/gallery/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/en/gallery/index.php",
	),
	array(
		"CONDITION" => "#^/info/video/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/info/video/index.php",
	),
	array(
		"CONDITION" => "#^/en/stores/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/en/stores/index.php",
	),
	array(
		"CONDITION" => "#^/en/sale/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/en/sale/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/catalog/index.php",
	),
	array(
		"CONDITION" => "#^/en/news/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/en/news/index.php",
	),
	array(
		"CONDITION" => "#^/gallery/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/gallery/index.php",
	),
	array(
		"CONDITION" => "#^/stores/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/stores/index.php",
	),
	array(
		"CONDITION" => "#^/sale/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/sale/index.php",
	),
	array(
		"CONDITION" => "#^/news/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/news/index.php",
	),
);

?>